package aplicacion.config;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.Operation;
import io.swagger.v3.oas.models.PathItem;
import io.swagger.v3.oas.models.Paths;
import io.swagger.v3.oas.models.media.*;
import io.swagger.v3.oas.models.parameters.Parameter;
import io.swagger.v3.oas.models.parameters.RequestBody;
import io.swagger.v3.oas.models.responses.ApiResponse;
import io.swagger.v3.oas.models.responses.ApiResponses;
import org.springdoc.core.models.GroupedOpenApi;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.util.List;

@Configuration
public class SwaggerConfig {
    @Bean
    public GroupedOpenApi manualApi() {
        return GroupedOpenApi.builder()
                .group("manual")
                .packagesToScan("")
                .build();
    }

    @Value("${api.administrativa.ip}")
    private String apiAdministrativaIp;

    @Bean
    public OpenAPI customOpenAPI() {
        Paths paths = new Paths();

        // ============= COLECCIONES =============
        paths.addPathItem("/apiAdministrativa/colecciones", new PathItem()
                .post(new Operation()
                        .tags(List.of("coleccion-controller"))
                        .summary("Crear una nueva colección")
                        .description("Crea una nueva colección con título, descripción, criterios de pertenencia, fuentes y algoritmo de consenso")
                        .requestBody(new RequestBody()
                                .required(true)
                                .content(new Content()
                                        .addMediaType("application/json",
                                                new MediaType()
                                                        .schema(new ObjectSchema()
                                                                .addProperty("titulo", new StringSchema().example("Desastres Naturales Argentina").maxLength(50))
                                                                .addProperty("descripcion", new StringSchema().example("Colección de desastres naturales ocurridos en Argentina").maxLength(150))
                                                                .addProperty("criteriosDePertenencia", new ArraySchema()
                                                                        .items(new ObjectSchema()
                                                                                .addProperty("tipo", new StringSchema().example("distancia").description("Puede ser 'distancia' o 'fecha'"))
                                                                        )
                                                                )
                                                                .addProperty("fuentes", new ArraySchema()
                                                                        .items(new ObjectSchema()
                                                                                .addProperty("tipo", new StringSchema().example("estatica").description("Puede ser 'estatica', 'dinamica' o 'proxy'"))
                                                                                .addProperty("id", new StringSchema().example("fuente-estatica-1").maxLength(255))
                                                                        )
                                                                )
                                                                .addProperty("tipoAlgoritmoConsenso", new StringSchema()
                                                                        .example("MAYORIA_SIMPLE")
                                                                        .description("Valores posibles: IRRESTRICTO, MAYORIA_SIMPLE, MULTIPLES_MENCIONES, ABSOLUTO")
                                                                        .maxLength(31)
                                                                )
                                                        )
                                        )
                                )
                        )
                        .responses(new ApiResponses()
                                .addApiResponse("201", new ApiResponse()
                                        .description("Colección creada exitosamente")
                                        .content(new Content()
                                                .addMediaType("application/json",
                                                        new MediaType()
                                                                .schema(new ObjectSchema()
                                                                        .addProperty("id", new StringSchema().example("col-123"))
                                                                        .addProperty("titulo", new StringSchema().example("Desastres Naturales Argentina"))
                                                                        .addProperty("descripcion", new StringSchema().example("Colección de desastres naturales ocurridos en Argentina"))
                                                                        .addProperty("criteriosDePertenencia", new ArraySchema().items(new ObjectSchema()))
                                                                        .addProperty("fuentes", new ArraySchema().items(new ObjectSchema()
                                                                                .addProperty("id", new StringSchema().example("fuente-1"))
                                                                                .addProperty("alias", new StringSchema().example("Fuente Estática"))
                                                                        ))
                                                                        .addProperty("tipoAlgoritmoConsenso", new StringSchema().example("MAYORIA_SIMPLE"))
                                                                )
                                                )
                                        )
                                )
                        )
                )
        );

        paths.addPathItem("/apiAdministrativa/colecciones/{id}", new PathItem()
                .delete(new Operation()
                        .tags(List.of("coleccion-controller"))
                        .summary("Eliminar una colección")
                        .description("Elimina una colección por su ID")
                        .addParametersItem(new Parameter()
                                .name("id")
                                .in("path")
                                .required(true)
                                .schema(new StringSchema())
                                .description("ID de la colección a eliminar")
                        )
                        .responses(new ApiResponses()
                                .addApiResponse("204", new ApiResponse().description("Colección eliminada exitosamente"))
                                .addApiResponse("404", new ApiResponse().description("Colección no encontrada"))
                        )
                )
        );

        paths.addPathItem("/apiAdministrativa/colecciones/{id}/algoritmo", new PathItem()
                .patch(new Operation()
                        .tags(List.of("coleccion-controller"))
                        .summary("Modificar algoritmo de consenso de una colección")
                        .description("Actualiza el algoritmo de consenso de una colección existente")
                        .addParametersItem(new Parameter()
                                .name("id")
                                .in("path")
                                .required(true)
                                .schema(new StringSchema())
                                .description("ID de la colección")
                        )
                        .requestBody(new RequestBody()
                                .required(true)
                                .content(new Content()
                                        .addMediaType("application/json",
                                                new MediaType()
                                                        .schema(new ObjectSchema()
                                                                .addProperty("algoritmoConsenso", new StringSchema()
                                                                        .example("ABSOLUTO")
                                                                        .description("Valores posibles: IRRESTRICTO, MAYORIA_SIMPLE, MULTIPLES_MENCIONES, ABSOLUTO")
                                                                        .maxLength(31)
                                                                )
                                                        )
                                        )
                                )
                        )
                        .responses(new ApiResponses()
                                .addApiResponse("200", new ApiResponse()
                                        .description("Algoritmo actualizado")
                                        .content(new Content()
                                                .addMediaType("application/json",
                                                        new MediaType()
                                                                .schema(new ObjectSchema()
                                                                        .addProperty("id", new StringSchema().example("col-123"))
                                                                        .addProperty("titulo", new StringSchema().example("Desastres Naturales Argentina"))
                                                                        .addProperty("descripcion", new StringSchema().example("Colección de desastres naturales"))
                                                                        .addProperty("tipoAlgoritmoConsenso", new StringSchema().example("ABSOLUTO"))
                                                                )
                                                )
                                        )
                                )
                        )
                )
        );

        paths.addPathItem("/apiAdministrativa/colecciones/{id}/fuentes", new PathItem()
                .post(new Operation()
                        .tags(List.of("coleccion-controller"))
                        .summary("Agregar fuente a una colección")
                        .description("Agrega una fuente de hechos a una colección existente")
                        .addParametersItem(new Parameter()
                                .name("id")
                                .in("path")
                                .required(true)
                                .schema(new StringSchema())
                                .description("ID de la colección")
                        )
                        .requestBody(new RequestBody()
                                .required(true)
                                .content(new Content()
                                        .addMediaType("application/json",
                                                new MediaType()
                                                        .schema(new ObjectSchema()
                                                                .addProperty("tipo", new StringSchema()
                                                                        .example("proxy")
                                                                        .description("Tipo de fuente: 'estatica', 'dinamica' o 'proxy'")
                                                                )
                                                                .addProperty("id", new StringSchema()
                                                                        .example("fuente-proxy-1")
                                                                        .description("ID de la fuente")
                                                                        .maxLength(255)
                                                                )
                                                        )
                                        )
                                )
                        )
                        .responses(new ApiResponses()
                                .addApiResponse("200", new ApiResponse()
                                        .description("Fuente agregada exitosamente")
                                        .content(new Content()
                                                .addMediaType("application/json",
                                                        new MediaType()
                                                                .schema(new ObjectSchema()
                                                                        .addProperty("id", new StringSchema().example("col-123"))
                                                                        .addProperty("titulo", new StringSchema().example("Desastres Naturales Argentina"))
                                                                        .addProperty("fuentes", new ArraySchema()
                                                                                .items(new ObjectSchema()
                                                                                        .addProperty("id", new StringSchema().example("fuente-1"))
                                                                                )
                                                                        )
                                                                )
                                                )
                                        )
                                )
                                .addApiResponse("404", new ApiResponse().description("Colección no encontrada"))
                        )
                )
        );

        paths.addPathItem("/apiAdministrativa/colecciones/{id}/fuentes/{fuenteId}", new PathItem()
                .delete(new Operation()
                        .tags(List.of("coleccion-controller"))
                        .summary("Quitar fuente de una colección")
                        .description("Elimina una fuente de hechos de una colección")
                        .addParametersItem(new Parameter()
                                .name("id")
                                .in("path")
                                .required(true)
                                .schema(new StringSchema())
                                .description("ID de la colección")
                        )
                        .addParametersItem(new Parameter()
                                .name("fuenteId")
                                .in("path")
                                .required(true)
                                .schema(new StringSchema())
                                .description("ID de la fuente a eliminar")
                        )
                        .responses(new ApiResponses()
                                .addApiResponse("200", new ApiResponse()
                                        .description("Fuente eliminada exitosamente")
                                        .content(new Content()
                                                .addMediaType("application/json",
                                                        new MediaType().schema(new ObjectSchema()
                                                                .addProperty("id", new StringSchema().example("col-123"))
                                                                .addProperty("fuentes", new ArraySchema().items(new ObjectSchema()))
                                                        )
                                                )
                                        )
                                )
                                .addApiResponse("404", new ApiResponse().description("Colección o fuente no encontrada"))
                        )
                )
        );

        // ============= SOLICITUDES =============
        paths.addPathItem("/apiAdministrativa/solicitudes", new PathItem()
                .get(new Operation()
                        .tags(List.of("solicitud-controller"))
                        .summary("Obtener solicitudes de eliminación")
                        .description("Devuelve la lista paginada de todas las solicitudes de eliminación de hechos")
                        .addParametersItem(new Parameter()
                                .name("page")
                                .in("query")
                                .required(false)
                                .schema(new IntegerSchema()._default(0))
                                .description("Número de página (comienza en 0)")
                        )
                        .addParametersItem(new Parameter()
                                .name("size")
                                .in("query")
                                .required(false)
                                .schema(new IntegerSchema()._default(3))
                                .description("Cantidad de elementos por página")
                        )
                        .responses(new ApiResponses()
                                .addApiResponse("200", new ApiResponse()
                                        .description("Lista de solicitudes")
                                        .content(new Content()
                                                .addMediaType("application/json",
                                                        new MediaType()
                                                                .schema(new ObjectSchema()
                                                                        .addProperty("content", new ArraySchema()
                                                                                .items(new ObjectSchema()
                                                                                        .addProperty("id", new IntegerSchema().example(1))
                                                                                        .addProperty("hechoId", new StringSchema().example("hecho-123"))
                                                                                        .addProperty("motivo", new StringSchema().example("Información incorrecta"))
                                                                                        .addProperty("estado", new ObjectSchema()
                                                                                                .addProperty("estado", new StringSchema().example("PENDIENTE"))
                                                                                        )
                                                                                        .addProperty("fechaSubida", new StringSchema().format("date-time").example("2025-12-01T10:30:00"))
                                                                                )
                                                                        )
                                                                        .addProperty("totalElements", new IntegerSchema().example(10))
                                                                        .addProperty("totalPages", new IntegerSchema().example(4))
                                                                        .addProperty("size", new IntegerSchema().example(3))
                                                                        .addProperty("number", new IntegerSchema().example(0))
                                                                )
                                                )
                                        )
                                )
                        )
                )
        );

        paths.addPathItem("/apiAdministrativa/solicitudes/{id}", new PathItem()
                .get(new Operation()
                        .tags(List.of("solicitud-controller"))
                        .summary("Obtener solicitud por ID")
                        .description("Devuelve los detalles de una solicitud específica")
                        .addParametersItem(new Parameter()
                                .name("id")
                                .in("path")
                                .required(true)
                                .schema(new IntegerSchema())
                                .description("ID de la solicitud")
                        )
                        .responses(new ApiResponses()
                                .addApiResponse("200", new ApiResponse()
                                        .description("Detalles de la solicitud")
                                        .content(new Content()
                                                .addMediaType("application/json",
                                                        new MediaType()
                                                                .schema(new ObjectSchema()
                                                                        .addProperty("id", new IntegerSchema().example(1))
                                                                        .addProperty("hechoId", new StringSchema().example("hecho-123"))
                                                                        .addProperty("motivo", new StringSchema().example("Información incorrecta"))
                                                                        .addProperty("estado", new ObjectSchema()
                                                                                .addProperty("estado", new StringSchema().example("PENDIENTE"))
                                                                        )
                                                                        .addProperty("fechaSubida", new StringSchema().format("date-time").example("2025-12-01T10:30:00"))
                                                                )
                                                )
                                        )
                                )
                        )
                )
        );

        paths.addPathItem("/apiAdministrativa/solicitudes/{id}/estado", new PathItem()
                .patch(new Operation()
                        .tags(List.of("solicitud-controller"))
                        .summary("Actualizar estado de una solicitud")
                        .description("Aprueba o deniega una solicitud de eliminación de un hecho")
                        .addParametersItem(new Parameter()
                                .name("id")
                                .in("path")
                                .required(true)
                                .schema(new IntegerSchema())
                                .description("ID de la solicitud")
                        )
                        .requestBody(new RequestBody()
                                .required(true)
                                .content(new Content()
                                        .addMediaType("application/json",
                                                new MediaType()
                                                        .schema(new ObjectSchema()
                                                                .addProperty("nuevoEstado", new StringSchema()
                                                                        .example("APROBADA")
                                                                        .description("Nuevo estado: APROBADA o DENEGADA")
                                                                        .maxLength(31)
                                                                )
                                                                .addProperty("adminId", new StringSchema()
                                                                        .example("admin-001")
                                                                        .description("ID del administrador que revisa la solicitud")
                                                                )
                                                        )
                                        )
                                )
                        )
                        .responses(new ApiResponses()
                                .addApiResponse("200", new ApiResponse().description("Estado actualizado exitosamente"))
                                .addApiResponse("400", new ApiResponse().description("Datos inválidos"))
                                .addApiResponse("404", new ApiResponse().description("Solicitud no encontrada"))
                        )
                )
        );

        // ============= HECHOS =============
        paths.addPathItem("/apiAdministrativa/cargarHechos", new PathItem()
                .post(new Operation()
                        .tags(List.of("hecho-controller"))
                        .summary("Cargar hechos desde fuentes")
                        .description("Solicita al agregador que cargue y procese hechos desde todas las fuentes registradas en las colecciones activas")
                        .responses(new ApiResponses()
                                .addApiResponse("200", new ApiResponse()
                                        .description("Carga de hechos iniciada exitosamente")
                                        .content(new Content()
                                                .addMediaType("application/json",
                                                        new MediaType()
                                                                .schema(new StringSchema()
                                                                        .example("Hechos cargados exitosamente desde todas las fuentes")
                                                                )
                                                )
                                        )
                                )
                                .addApiResponse("500", new ApiResponse()
                                        .description("Error al cargar hechos desde las fuentes")
                                )
                        )
                )
        );

        paths.addPathItem("/apiAdministrativa/hechos", new PathItem()
                .post(new Operation()
                        .tags(List.of("hecho-controller"))
                        .summary("Reportar un nuevo hecho")
                        .description("Crea un nuevo hecho manualmente (carga manual por administrador)")
                        .requestBody(new RequestBody()
                                .required(true)
                                .content(new Content()
                                        .addMediaType("application/json",
                                                new MediaType()
                                                        .schema(new ObjectSchema()
                                                                .addProperty("titulo", new StringSchema().example("Inundación en Buenos Aires").maxLength(200))
                                                                .addProperty("descripcion", new StringSchema().example("Fuertes lluvias causaron inundaciones en la ciudad").maxLength(1000))
                                                                .addProperty("categoria", new ObjectSchema()
                                                                        .addProperty("nombre", new StringSchema().example("Inundación").maxLength(50))
                                                                )
                                                                .addProperty("ubicacion", new ObjectSchema()
                                                                        .addProperty("latitud", new NumberSchema().example(-34.6037))
                                                                        .addProperty("longitud", new NumberSchema().example(-58.3816))
                                                                )
                                                                .addProperty("fechaAcontecimiento", new StringSchema()
                                                                        .format("date-time")
                                                                        .example("2025-12-01T15:30:00")
                                                                )
                                                                .addProperty("origen", new StringSchema()
                                                                        .example("CARGA_MANUAL")
                                                                        .description("Valores: CARGA_MANUAL, DATASET, CONTRIBUYENTE, EXTERNO")
                                                                        .maxLength(255)
                                                                )
                                                                .addProperty("contenidoTexto", new StringSchema()
                                                                        .example("Descripción detallada del hecho")
                                                                        .maxLength(500)
                                                                )
                                                                .addProperty("anonimato", new BooleanSchema().example(false))
                                                                .addProperty("contenidoMultimedia", new ArraySchema()
                                                                        .items(new ObjectSchema()
                                                                                .addProperty("url", new StringSchema()
                                                                                        .example("https://example.com/imagen.jpg")
                                                                                        .maxLength(500)
                                                                                )
                                                                        )
                                                                )
                                                                .addProperty("autor", new StringSchema()
                                                                        .example("admin-001")
                                                                        .description("ID del contribuyente autor")
                                                                )
                                                        )
                                        )
                                )
                        )
                        .responses(new ApiResponses()
                                .addApiResponse("201", new ApiResponse()
                                        .description("Hecho creado exitosamente")
                                        .content(new Content()
                                                .addMediaType("application/json",
                                                        new MediaType()
                                                                .schema(new ObjectSchema()
                                                                        .addProperty("id", new StringSchema().example("hecho-123"))
                                                                        .addProperty("titulo", new StringSchema().example("Inundación en Buenos Aires"))
                                                                        .addProperty("descripcion", new StringSchema().example("Fuertes lluvias causaron inundaciones"))
                                                                        .addProperty("categoria", new ObjectSchema()
                                                                                .addProperty("id", new IntegerSchema().example(1))
                                                                                .addProperty("nombre", new StringSchema().example("Inundación"))
                                                                        )
                                                                        .addProperty("origen", new StringSchema().example("CARGA_MANUAL"))
                                                                        .addProperty("fechaCarga", new StringSchema().format("date-time"))
                                                                )
                                                )
                                        )
                                )
                        )
                )
        );

        paths.addPathItem("/apiAdministrativa/hechos/{id}", new PathItem()
                .patch(new Operation()
                        .tags(List.of("hecho-controller"))
                        .summary("Editar un hecho existente")
                        .description("Permite a los administradores editar los campos de un hecho existente")
                        .addParametersItem(new Parameter()
                                .name("id")
                                .in("path")
                                .required(true)
                                .schema(new StringSchema())
                                .description("ID del hecho a editar")
                        )
                        .requestBody(new RequestBody()
                                .required(true)
                                .content(new Content()
                                        .addMediaType("application/json",
                                                new MediaType()
                                                        .schema(new ObjectSchema()
                                                                .addProperty("titulo", new StringSchema().example("Título actualizado del hecho").maxLength(200))
                                                                .addProperty("descripcion", new StringSchema().example("Descripción actualizada del hecho").maxLength(1000))
                                                                .addProperty("categoria", new ObjectSchema()
                                                                        .addProperty("nombre", new StringSchema().example("Terremoto").maxLength(50))
                                                                )
                                                                .addProperty("ubicacion", new ObjectSchema()
                                                                        .addProperty("latitud", new NumberSchema().example(-34.6037))
                                                                        .addProperty("longitud", new NumberSchema().example(-58.3816))
                                                                )
                                                                .addProperty("fechaAcontecimiento", new StringSchema()
                                                                        .format("date-time")
                                                                        .example("2025-12-04T10:00:00")
                                                                )
                                                                .addProperty("contenidoTexto", new StringSchema()
                                                                        .example("Contenido actualizado del hecho")
                                                                        .maxLength(500)
                                                                )
                                                                .addProperty("contenidoMultimedia", new ArraySchema()
                                                                        .items(new ObjectSchema()
                                                                                .addProperty("url", new StringSchema()
                                                                                        .example("https://example.com/imagen-actualizada.jpg")
                                                                                        .maxLength(500)
                                                                                )
                                                                        )
                                                                )
                                                        )
                                        )
                                )
                        )
                        .responses(new ApiResponses()
                                .addApiResponse("200", new ApiResponse()
                                        .description("Hecho editado exitosamente")
                                        .content(new Content()
                                                .addMediaType("application/json",
                                                        new MediaType()
                                                                .schema(new ObjectSchema()
                                                                        .addProperty("id", new StringSchema().example("hecho-123"))
                                                                        .addProperty("titulo", new StringSchema().example("Título actualizado del hecho"))
                                                                        .addProperty("descripcion", new StringSchema().example("Descripción actualizada del hecho"))
                                                                        .addProperty("categoria", new ObjectSchema()
                                                                                .addProperty("id", new IntegerSchema().example(2))
                                                                                .addProperty("nombre", new StringSchema().example("Terremoto"))
                                                                        )
                                                                        .addProperty("ubicacion", new ObjectSchema()
                                                                                .addProperty("latitud", new NumberSchema().example(-34.6037))
                                                                                .addProperty("longitud", new NumberSchema().example(-58.3816))
                                                                        )
                                                                        .addProperty("fechaAcontecimiento", new StringSchema().format("date-time"))
                                                                )
                                                )
                                        )
                                )
                                .addApiResponse("404", new ApiResponse().description("Hecho no encontrado"))
                                .addApiResponse("400", new ApiResponse().description("Datos de entrada inválidos"))
                        )
                )
        );

        paths.addPathItem("/apiAdministrativa/hechos/{id}/tags", new PathItem()
                .post(new Operation()
                        .tags(List.of("hecho-controller"))
                        .summary("Agregar etiqueta a un hecho")
                        .description("Agrega una etiqueta (tag) a un hecho existente")
                        .addParametersItem(new Parameter()
                                .name("id")
                                .in("path")
                                .required(true)
                                .schema(new StringSchema())
                                .description("ID del hecho")
                        )
                        .requestBody(new RequestBody()
                                .required(true)
                                .content(new Content()
                                        .addMediaType("application/json",
                                                new MediaType()
                                                        .schema(new StringSchema().example("urgente"))
                                        )
                                )
                        )
                        .responses(new ApiResponses()
                                .addApiResponse("200", new ApiResponse()
                                        .description("Etiqueta agregada exitosamente")
                                        .content(new Content()
                                                .addMediaType("application/json",
                                                        new MediaType()
                                                                .schema(new ObjectSchema()
                                                                        .addProperty("nombre", new StringSchema().example("urgente"))
                                                                )
                                                )
                                        )
                                )
                                .addApiResponse("404", new ApiResponse().description("Hecho no encontrado"))
                        )
                )
        );

        paths.addPathItem("/apiAdministrativa/hechos/{id}/tags/{nombreTag}", new PathItem()
                .delete(new Operation()
                        .tags(List.of("hecho-controller"))
                        .summary("Quitar etiqueta de un hecho")
                        .description("Elimina una etiqueta específica de un hecho")
                        .addParametersItem(new Parameter()
                                .name("id")
                                .in("path")
                                .required(true)
                                .schema(new StringSchema())
                                .description("ID del hecho")
                        )
                        .addParametersItem(new Parameter()
                                .name("nombreTag")
                                .in("path")
                                .required(true)
                                .schema(new StringSchema())
                                .description("Nombre de la etiqueta a eliminar")
                        )
                        .responses(new ApiResponses()
                                .addApiResponse("204", new ApiResponse().description("Etiqueta eliminada exitosamente"))
                                .addApiResponse("404", new ApiResponse().description("Hecho o etiqueta no encontrados"))
                        )
                )
        );

        // ============= FUENTES =============
        paths.addPathItem("/apiAdministrativa/fuentes", new PathItem()
                .get(new Operation()
                        .tags(List.of("fuente-controller"))
                        .summary("Obtener fuentes disponibles")
                        .description("Devuelve la lista paginada de todas las fuentes de hechos registradas en el sistema, con filtrado opcional por tipo")
                        .addParametersItem(new Parameter()
                                .name("tipo")
                                .in("query")
                                .required(false)
                                .schema(new StringSchema())
                                .description("Tipo de fuente para filtrar: 'estatica', 'dinamica' o 'proxy'")
                                .example("estatica")
                        )
                        .addParametersItem(new Parameter()
                                .name("page")
                                .in("query")
                                .required(false)
                                .schema(new IntegerSchema()._default(0))
                                .description("Número de página (comienza en 0)")
                        )
                        .addParametersItem(new Parameter()
                                .name("limit")
                                .in("query")
                                .required(false)
                                .schema(new IntegerSchema()._default(10))
                                .description("Cantidad de elementos por página")
                        )
                        .responses(new ApiResponses()
                                .addApiResponse("200", new ApiResponse()
                                        .description("Lista de fuentes obtenida exitosamente")
                                        .content(new Content()
                                                .addMediaType("application/json",
                                                        new MediaType()
                                                                .schema(new ObjectSchema()
                                                                        .addProperty("content", new ArraySchema()
                                                                                .items(new ObjectSchema()
                                                                                        .addProperty("id", new StringSchema().example("fuente-estatica-1"))
                                                                                        .addProperty("alias", new StringSchema().example("Fuente de Desastres Naturales"))
                                                                                        .addProperty("tipo", new StringSchema().example("ESTATICA").description("ESTATICA, DINAMICA o PROXY"))
                                                                                        .addProperty("activa", new BooleanSchema().example(true))
                                                                                )
                                                                        )
                                                                        .addProperty("totalElements", new IntegerSchema().example(25))
                                                                        .addProperty("totalPages", new IntegerSchema().example(3))
                                                                        .addProperty("size", new IntegerSchema().example(10))
                                                                        .addProperty("number", new IntegerSchema().example(0))
                                                                )
                                                )
                                        )
                                )
                        )
                )
        );

        // ============= FUENTES ESTÁTICAS =============
        paths.addPathItem("/apiAdministrativa/archivos/por-url", new PathItem()
                .post(new Operation()
                        .tags(List.of("fuente-estatica-controller"))
                        .summary("Subir archivo desde URL")
                        .description("Carga un archivo CSV desde una URL externa al servidor de archivos")
                        .requestBody(new RequestBody()
                                .required(true)
                                .content(new Content()
                                        .addMediaType("application/json",
                                                new MediaType()
                                                        .schema(new StringSchema()
                                                                .example("https://example.com/datos.csv")
                                                                .maxLength(5000)
                                                                .description("URL del archivo a cargar")
                                                        )
                                        )
                                )
                        )
                        .responses(new ApiResponses()
                                .addApiResponse("201", new ApiResponse()
                                        .description("Archivo subido correctamente")
                                        .content(new Content()
                                                .addMediaType("application/json",
                                                        new MediaType()
                                                                .schema(new StringSchema().example("Archivo subido correctamente desde URL al FileServer"))
                                                )
                                        )
                                )
                                .addApiResponse("500", new ApiResponse().description("Error al subir archivo"))
                        )
                )
        );

        paths.addPathItem("/apiAdministrativa/archivos", new PathItem()
                .post(new Operation()
                        .tags(List.of("fuente-estatica-controller"))
                        .summary("Subir archivos CSV")
                        .description("Carga uno o múltiples archivos CSV al servidor de archivos")
                        .requestBody(new RequestBody()
                                .required(true)
                                .content(new Content()
                                        .addMediaType("multipart/form-data",
                                                new MediaType()
                                                        .schema(new ObjectSchema()
                                                                .addProperty("files", new ArraySchema()
                                                                        .items(new StringSchema().format("binary"))
                                                                        .description("Archivos CSV a subir")
                                                                )
                                                        )
                                        )
                                )
                        )
                        .responses(new ApiResponses()
                                .addApiResponse("201", new ApiResponse()
                                        .description("Archivos subidos correctamente")
                                        .content(new Content()
                                                .addMediaType("application/json",
                                                        new MediaType()
                                                                .schema(new StringSchema().example("Archivos subidos correctamente al FileServer"))
                                                )
                                        )
                                )
                                .addApiResponse("500", new ApiResponse().description("Error al subir archivos"))
                        )
                )
        );

        // ============= FUENTES PROXY =============
        paths.addPathItem("/apiAdministrativa/fuentesProxy", new PathItem()
                .post(new Operation()
                        .tags(List.of("fuente-proxy-controller"))
                        .summary("Guardar fuente proxy")
                        .description("Registra una nueva fuente proxy externa para importar hechos. Requiere especificar el tipo de fuente proxy mediante el parámetro 'tipo'.")
                        .addParametersItem(new Parameter()
                                .name("tipo")
                                .in("query")
                                .required(true)
                                .schema(new StringSchema()
                                        .example("demo")
                                        .description("Tipo de fuente proxy: 'demo' para fuentes de demostración o 'metamapa' para fuentes de otros servicios Metamapa")
                                        ._enum(List.of("demo", "metamapa"))
                                )
                                .description("Tipo de fuente proxy a registrar")
                        )
                        .requestBody(new RequestBody()
                                .required(true)
                                .content(new Content()
                                        .addMediaType("application/json",
                                                new MediaType()
                                                        .schema(new ObjectSchema()
                                                                .addProperty("biblioteca", new ObjectSchema()
                                                                        .addProperty("tipo", new StringSchema()
                                                                                .example("prueba")
                                                                                .description("Tipo de conexión a la biblioteca externa")
                                                                        )
                                                                        .description("Configuración de la conexión a la fuente externa")
                                                                )
                                                                .addProperty("url", new StringSchema()
                                                                        .example("https://api.externa.com/hechos")
                                                                        .maxLength(1000)
                                                                        .description("URL de la API externa")
                                                                )
                                                        )
                                        )
                                )
                        )
                        .responses(new ApiResponses()
                                .addApiResponse("201", new ApiResponse()
                                        .description("Fuente proxy guardada exitosamente")
                                        .content(new Content()
                                                .addMediaType("application/json",
                                                        new MediaType()
                                                                .schema(new ObjectSchema()
                                                                        .addProperty("id", new StringSchema().example("proxy-123"))
                                                                )
                                                )
                                        )
                                )
                                .addApiResponse("400", new ApiResponse()
                                        .description("Tipo de fuente no válido. Debe ser 'demo' o 'metamapa'")
                                        .content(new Content()
                                                .addMediaType("application/json",
                                                        new MediaType()
                                                                .schema(new StringSchema().example("Tipo de fuente no válido"))
                                                )
                                        )
                                )
                        )
                )
        );

        // ============= OBTENER HECHOS CON FILTROS =============
        paths.addPathItem("/apiAdministrativa/hechos", new PathItem()
                .get(new Operation()
                        .tags(List.of("hecho-controller"))
                        .summary("Obtener hechos con filtros")
                        .description("Obtiene hechos paginados filtrados por fecha o estado de revisión (pendientes)")
                        .addParametersItem(new Parameter()
                                .name("fechaMayorA")
                                .in("query")
                                .required(false)
                                .description("Filtra hechos con fecha de acontecimiento mayor a esta fecha (formato ISO: yyyy-MM-dd'T'HH:mm:ss)")
                                .schema(new StringSchema().example("2024-01-01T00:00:00"))
                        )
                        .addParametersItem(new Parameter()
                                .name("pendiente")
                                .in("query")
                                .required(false)
                                .description("Si es true, obtiene solo hechos pendientes de revisión")
                                .schema(new BooleanSchema()._default(false).example(false))
                        )
                        .addParametersItem(new Parameter()
                                .name("page")
                                .in("query")
                                .required(false)
                                .schema(new IntegerSchema()._default(0))
                                .description("Número de página (base 0)")
                        )
                        .addParametersItem(new Parameter()
                                .name("size")
                                .in("query")
                                .required(false)
                                .schema(new IntegerSchema()._default(10))
                                .description("Cantidad de elementos por página")
                        )
                        .responses(new ApiResponses()
                                .addApiResponse("200", new ApiResponse()
                                        .description("Lista de hechos obtenida exitosamente")
                                        .content(new Content()
                                                .addMediaType("application/json",
                                                        new MediaType()
                                                                .schema(new ArraySchema()
                                                                        .items(new ObjectSchema()
                                                                                .addProperty("id", new StringSchema().example("hecho-123"))
                                                                                .addProperty("titulo", new StringSchema().example("Inundación en Buenos Aires"))
                                                                                .addProperty("descripcion", new StringSchema().example("Inundación severa en zona norte"))
                                                                                .addProperty("fechaAcontecimiento", new StringSchema().example("2024-01-15T10:30:00"))
                                                                                .addProperty("estadoRevision", new StringSchema().example("PENDIENTE").description("PENDIENTE, ACEPTADO o RECHAZADO"))
                                                                        )
                                                                )
                                                )
                                        )
                                )
                        )
                )
        );

        // ============= ESTADÍSTICAS =============
        paths.addPathItem("/apiAdministrativa/estadisticas/actualizar", new PathItem()
                .post(new Operation()
                        .tags(List.of("estadisticas-controller"))
                        .summary("Actualizar estadísticas")
                        .description("Solicita al servicio de estadísticas que actualice todos los cálculos y métricas del sistema")
                        .responses(new ApiResponses()
                                .addApiResponse("200", new ApiResponse()
                                        .description("Estadísticas actualizadas exitosamente")
                                        .content(new Content()
                                                .addMediaType("application/json",
                                                        new MediaType()
                                                                .schema(new StringSchema()
                                                                        .example("Estadísticas actualizadas correctamente")
                                                                )
                                                )
                                        )
                                )
                                .addApiResponse("500", new ApiResponse()
                                        .description("Error al actualizar las estadísticas")
                                )
                        )
                )
        );

        // ============= MODIFICAR ESTADO DE REVISIÓN =============
        paths.addPathItem("/apiAdministrativa/hechos/{id}/estadoRevision", new PathItem()
                .patch(new Operation()
                        .tags(List.of("hecho-controller"))
                        .summary("Modificar estado de revisión de un hecho")
                        .description("Actualiza el estado de revisión de un hecho (PENDIENTE, ACEPTADO, RECHAZADO)")
                        .addParametersItem(new Parameter()
                                .name("id")
                                .in("path")
                                .required(true)
                                .description("ID del hecho")
                                .schema(new StringSchema().example("hecho-123"))
                        )
                        .requestBody(new RequestBody()
                                .required(true)
                                .content(new Content()
                                        .addMediaType("application/json",
                                                new MediaType()
                                                        .schema(new ObjectSchema()
                                                                .addProperty("estado", new StringSchema()
                                                                        .example("ACEPTADO")
                                                                        .description("Estado de revisión: PENDIENTE, ACEPTADO o RECHAZADO")
                                                                        .maxLength(255)
                                                                )
                                                                .addProperty("sugerencia", new StringSchema()
                                                                        .example("Verificar datos de ubicación")
                                                                        .description("Sugerencia opcional para el contribuyente (solo si estado es ACEPTADO)")
                                                                        .maxLength(255)
                                                                )
                                                        )
                                        )
                                )
                        )
                        .responses(new ApiResponses()
                                .addApiResponse("200", new ApiResponse()
                                        .description("Estado de revisión actualizado exitosamente")
                                        .content(new Content()
                                                .addMediaType("application/json",
                                                        new MediaType()
                                                                .schema(new ObjectSchema()
                                                                        .addProperty("id", new StringSchema().example("hecho-123"))
                                                                        .addProperty("titulo", new StringSchema().example("Inundación en Buenos Aires"))
                                                                        .addProperty("estadoRevision", new StringSchema().example("ACEPTADO"))
                                                                        .addProperty("sugerencia", new StringSchema().example("Verificar datos de ubicación"))
                                                                )
                                                )
                                        )
                                )
                                .addApiResponse("404", new ApiResponse()
                                        .description("Hecho no encontrado")
                                )
                        )
                )
        );

        // ============= HEALTH CHECK =============
        paths.addPathItem("/health", new PathItem()
                .get(new Operation()
                        .tags(List.of("health-controller"))
                        .summary("Health check del servicio")
                        .description("Verifica que el servicio de API Administrativa esté funcionando correctamente")
                        .responses(new ApiResponses()
                                .addApiResponse("200", new ApiResponse()
                                        .description("Servicio funcionando correctamente")
                                        .content(new Content()
                                                .addMediaType("application/json",
                                                        new MediaType()
                                                                .schema(new ObjectSchema()
                                                                        .addProperty("status", new StringSchema().example("ok"))
                                                                )
                                                )
                                        )
                                )
                        )
                )
        );

        return new OpenAPI()
                .info(new io.swagger.v3.oas.models.info.Info()
                        .title("API Administrativa de Metamapa")
                        .version("1.0")
                        .description("""
                                ### API Administrativa de Metamapa
                                
                                Esta API proporciona funcionalidades administrativas para gestionar el sistema Metamapa:
                                
                                #### Funcionalidades principales:
                                * **Operaciones CRUD sobre colecciones**: Crear, modificar y eliminar colecciones de hechos
                                * **Modificación del algoritmo de consenso**: Cambiar el algoritmo de curación de hechos en colecciones
                                * **Gestión de fuentes**: Agregar o quitar fuentes de hechos de una colección
                                * **Gestión de solicitudes**: Aprobar o denegar solicitudes de eliminación de hechos
                                * **Gestión de hechos**: Reportar hechos manualmente y administrar etiquetas
                                * **Carga de fuentes estáticas**: Subir archivos CSV desde URLs o directamente
                                * **Registro de fuentes proxy**: Conectar fuentes externas para importar hechos
                                * **Actualización de estadísticas**: Solicitar recálculo de métricas y estadísticas del sistema
                                
                                #### Tipos de Algoritmos de Consenso:
                                * **IRRESTRICTO**: Muestra todos los hechos sin filtrado
                                * **MAYORIA_SIMPLE**: Muestra hechos reportados por más del 50% de las fuentes
                                * **MULTIPLES_MENCIONES**: Muestra hechos reportados por al menos 2 fuentes
                                * **ABSOLUTO**: Muestra solo hechos reportados por todas las fuentes
                                
                                #### Tipos de Fuentes:
                                * **Estáticas**: Archivos CSV cargados al sistema
                                * **Dinámicas**: Hechos reportados por contribuyentes
                                * **Proxy**: APIs externas que proveen hechos
                                """)
                        .contact(new io.swagger.v3.oas.models.info.Contact()
                                .name("DDS K3002 Grupo 2")
                                .email("aherzkovich@frba.utn.edu.ar"))
                        .license(new io.swagger.v3.oas.models.info.License()
                                .name("MIT")
                                .url("https://opensource.org/licenses/MIT"))
                )
                .servers(List.of(
                        new io.swagger.v3.oas.models.servers.Server()
                                .url("http://" + apiAdministrativaIp + ":8086")
                                .description("Servidor de desarrollo")
                ))
                .paths(paths);
    }
}