package aplicacion.config;
import io.swagger.v3.oas.models.parameters.Parameter;
import io.swagger.v3.oas.models.parameters.RequestBody;
import io.swagger.v3.oas.models.responses.ApiResponses;
import io.swagger.v3.oas.models.media.*;
import org.springdoc.core.models.GroupedOpenApi;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import io.swagger.v3.oas.models.*;
import io.swagger.v3.oas.models.Operation;
import io.swagger.v3.oas.models.media.StringSchema;
import io.swagger.v3.oas.models.responses.ApiResponse;


import java.util.List;

@Configuration
public class SwaggerConfig {
    // Se puede usar para borrar todos los paths no manuales

    @Bean
    public GroupedOpenApi manualApi() {
        return GroupedOpenApi.builder()
                .group("manual")
                .packagesToScan("")
                .build();
    }
    @Bean
    public OpenAPI customOpenAPI() {

        Paths paths = new Paths();
        paths.addPathItem("/apiPublica/solicitudes", new PathItem()
                .post(new Operation()
                        .tags(List.of("solicitud-controller"))
                        .summary("Crear una nueva solicitud")
                        .description("Crea una solicitud con solicitanteId, hechoId y motivo")
                        .requestBody(new io.swagger.v3.oas.models.parameters.RequestBody()
                                .required(true)
                                .content(new Content()
                                        .addMediaType("application/json",
                                                new MediaType()
                                                        .schema(new ObjectSchema()
                                                                .addProperty("solicitanteId", new IntegerSchema().example(0))
                                                                .addProperty("hechoId", new StringSchema().example("string"))
                                                                .addProperty("motivo", new StringSchema().example(
                                                                        "En los anales de nuestro reino, todo acto que busque la supresión de un registro o la eliminación de un documento se ha de considerar con sumo cuidado, pues cada acción deja su impronta en el vasto libro de la memoria del reino. No basta con un mero capricho o la impaciencia del instante; es menester que quien solicita tal acción exponga con claridad y sobrada razón los fundamentos que la sustentan, describiendo los hechos, las causas y las consecuencias, de modo que los guardianes de la memoria puedan ponderar y juzgar con justicia la petición. Por mandato antiguo, se requiere que la justificación contenga no menos de quinientos caracteres, para que quede patente que la solicitud está debidamente reflexionada y fundamentada, asegurando así que la verdad y la equidad prevalezcan, y evitando que la sombra de la negligencia o de la precipitación borre de manera irremisible aquello que podría tener valor para generaciones futuras, pues la historia enseña que cada omisión mal fundamentada puede traer penurias y desdén sobre los que gobiernan y preservan el archivo del reino."
                                                                )))
                                        )
                                )
                        )
                        .responses(new ApiResponses()
                                .addApiResponse("200", new ApiResponse()
                                        .description("OK")
                                        .content(new Content()
                                                .addMediaType("application/json",
                                                        new MediaType()
                                                                .schema(new ObjectSchema()
                                                                        .addProperty("id", new IntegerSchema().example(0))
                                                                        .addProperty("solicitanteId", new IntegerSchema().example(0))
                                                                        .addProperty("hechoId", new StringSchema().example("string"))
                                                                        .addProperty("motivo", new StringSchema().example("string"))
                                                                        .addProperty("estado", new ObjectSchema()
                                                                                .addProperty("estado", new StringSchema().example("string"))
                                                                        )
                                                                        .addProperty("fechaSubida", new StringSchema().example("2025-11-28T23:10:19.848Z"))
                                                                )
                                                )
                                        )
                                )
                        )
                ));
        paths.addPathItem("/apiPublica/contribuyentes", new PathItem()
                .get(new Operation()
                        .operationId("obtenerContribuyentes")
                        .tags(List.of("contribuyente-controller"))
                        .summary("Obtener contribuyentes")
                        .description("Devuelve la lista de todos los contribuyentes, opcionalmente filtrando por mail")
                        .addParametersItem(new Parameter()
                                .name("mail")
                                .in("query")
                                .description("Filtra contribuyentes por mail")
                                .required(false)
                                .schema(new StringSchema())
                        )
                        .responses(new ApiResponses()
                                .addApiResponse("200", new ApiResponse()
                                        .description("OK")
                                        .content(new Content().addMediaType("application/json",
                                                new MediaType().schema(
                                                        new ArraySchema()
                                                                .items(new ObjectSchema()
                                                                        .addProperty("esAdministrador", new BooleanSchema().example(true))
                                                                        .addProperty("identidad", new ObjectSchema()
                                                                                .addProperty("nombre", new StringSchema().example("string"))
                                                                                .addProperty("apellido", new StringSchema().example("string"))
                                                                                .addProperty("fechaNacimiento", new StringSchema().format("date").example("2025-11-28"))
                                                                        )
                                                                        .addProperty("mail", new StringSchema().example("string"))
                                                                )
                                                )
                                        ))
                                )
                        )
                )
                .post(new Operation()
                        .operationId("crearContribuyente")
                        .tags(List.of("contribuyente-controller"))
                        .summary("Crear contribuyente")
                        .description("Crea un nuevo contribuyente")
                        .requestBody(new RequestBody()
                                .required(true)
                                .content(new Content().addMediaType("application/json",
                                        new MediaType().schema(new ObjectSchema()
                                                .addProperty("esAdministrador", new BooleanSchema().example(true))
                                                .addProperty("identidad", new ObjectSchema()
                                                        .addProperty("nombre", new StringSchema().example("string"))
                                                        .addProperty("apellido", new StringSchema().example("string"))
                                                        .addProperty("fechaNacimiento", new StringSchema().format("date").example("2025-11-28"))
                                                )
                                                .addProperty("mail", new StringSchema().example("string"))
                                        )
                                ))
                        )
                        .responses(new ApiResponses()
                                .addApiResponse("200", new ApiResponse()
                                        .description("Contribuyente creado")
                                        .content(new Content().addMediaType("application/json",
                                                new MediaType().schema(new ObjectSchema()
                                                        .addProperty("esAdministrador", new BooleanSchema().example(true))
                                                        .addProperty("identidad", new ObjectSchema()
                                                                .addProperty("nombre", new StringSchema().example("string"))
                                                                .addProperty("apellido", new StringSchema().example("string"))
                                                                .addProperty("fechaNacimiento", new StringSchema().format("date").example("2025-11-28"))
                                                        )
                                                        .addProperty("mail", new StringSchema().example("string"))
                                                )
                                        ))
                                )
                        )
                )
        );

        paths.addPathItem("/apiPublica/contribuyentes/{id}/identidad", new PathItem()
                .patch(new Operation()
                        .tags(List.of("contribuyente-controller"))
                        .summary("Modificar identidad de un contribuyente")
                        .description("Actualiza la información de identidad de un contribuyente existente")
                        .addParametersItem(new Parameter()
                                .name("id")
                                .in("path")
                                .required(true)
                                .schema(new UUIDSchema())
                                .description("ID del contribuyente")
                        )
                        .requestBody(new RequestBody()
                                .required(true)
                                .content(new Content().addMediaType("application/json",
                                        new MediaType().schema(new ObjectSchema()
                                                .addProperty("nombre", new StringSchema().example("Agustin"))
                                                .addProperty("apellido", new StringSchema().example("Herzkovich"))
                                                .addProperty("fechaNacimiento", new StringSchema().example("2005-11-29"))
                                        )
                                ))
                        )
                        .responses(new ApiResponses()
                                .addApiResponse("200", new ApiResponse().description("Identidad actualizada"))
                        )
                )
        );

        paths.addPathItem("/apiPublica/contribuyentes/{id}/hechos", new PathItem()
                .get(new Operation()
                        .tags(List.of("contribuyente-controller"))
                        .summary("Obtener hechos de un contribuyente")
                        .description("Devuelve la lista de hechos asociados a un contribuyente")
                        .addParametersItem(new Parameter()
                                .name("id")
                                .in("path")
                                .required(true)
                                .schema(new IntegerSchema())
                                .description("ID del contribuyente")
                        )
                        .responses(new ApiResponses()
                                .addApiResponse("200", new ApiResponse()
                                        .description("OK")
                                        .content(new Content().addMediaType("application/json",
                                                new MediaType().schema(
                                                        new ArraySchema()
                                                                .items(new ObjectSchema()
                                                                        .addProperty("id", new StringSchema().example("string"))
                                                                        .addProperty("titulo", new StringSchema().example("string"))
                                                                        .addProperty("descripcion", new StringSchema().example("string"))
                                                                        .addProperty("categoria", new ObjectSchema()
                                                                                .addProperty("id", new IntegerSchema().example(0))
                                                                                .addProperty("nombre", new StringSchema().example("string"))
                                                                        )
                                                                        .addProperty("ubicacion", new ObjectSchema()
                                                                                .addProperty("latitud", new NumberSchema().example(0))
                                                                                .addProperty("longitud", new NumberSchema().example(0))
                                                                        )
                                                                        .addProperty("fechaAcontecimiento", new StringSchema().format("date-time").example("2025-11-29T00:04:33.303Z"))
                                                                        .addProperty("fechaCarga", new StringSchema().format("date-time").example("2025-11-29T00:04:33.303Z"))
                                                                        .addProperty("fechaUltimaModificacion", new StringSchema().format("date-time").example("2025-11-29T00:04:33.303Z"))
                                                                        .addProperty("origen", new StringSchema().example("CARGA_MANUAL"))
                                                                        .addProperty("contenidoTexto", new StringSchema().example("string"))
                                                                        .addProperty("contenidoMultimedia", new ArraySchema()
                                                                                .items(new ObjectSchema()
                                                                                        .addProperty("id", new IntegerSchema().example(0))
                                                                                        .addProperty("url", new StringSchema().example("string"))
                                                                                )
                                                                        )
                                                                        .addProperty("anonimato", new BooleanSchema().example(true))
                                                                        .addProperty("autor", new ObjectSchema()
                                                                                .addProperty("id", new IntegerSchema().example(0))
                                                                                .addProperty("esAdministrador", new BooleanSchema().example(true))
                                                                                .addProperty("identidad", new ObjectSchema()
                                                                                        .addProperty("nombre", new StringSchema().example("string"))
                                                                                        .addProperty("apellido", new StringSchema().example("string"))
                                                                                        .addProperty("fechaNacimiento", new StringSchema().format("date").example("2025-11-29"))
                                                                                )
                                                                                .addProperty("mail", new StringSchema().example("string"))
                                                                        )
                                                                        .addProperty("etiquetas", new ArraySchema()
                                                                                .items(new ObjectSchema()
                                                                                        .addProperty("nombre", new StringSchema().example("string"))
                                                                                )
                                                                        )
                                                                )
                                                )
                                        ))
                                )
                        )
                )
        );
// ApiResponse reutilizable para lista paginada de hechos
        ApiResponse paginatedHechosResponse = new ApiResponse()
                .description("Lista paginada de hechos")
                .content(new Content().addMediaType("application/json",
                        new MediaType().schema(
                                new ObjectSchema()
                                        .addProperty("totalElements", new IntegerSchema().example(0))
                                        .addProperty("totalPages", new IntegerSchema().example(0))
                                        .addProperty("first", new BooleanSchema().example(true))
                                        .addProperty("last", new BooleanSchema().example(true))
                                        .addProperty("size", new IntegerSchema().example(0))
                                        .addProperty("content", new ArraySchema()
                                                .items(new ObjectSchema()
                                                        .addProperty("id", new StringSchema().example("string"))
                                                        .addProperty("titulo", new StringSchema().example("string"))
                                                        .addProperty("descripcion", new StringSchema().example("string"))
                                                        .addProperty("categoria", new ObjectSchema()
                                                                .addProperty("id", new IntegerSchema().example(0))
                                                                .addProperty("nombre", new StringSchema().example("string"))
                                                        )
                                                        .addProperty("ubicacion", new ObjectSchema()
                                                                .addProperty("latitud", new NumberSchema().example(0))
                                                                .addProperty("longitud", new NumberSchema().example(0))
                                                        )
                                                        .addProperty("fechaAcontecimiento", new StringSchema().format("date-time").example("2025-11-29T00:06:57.260Z"))
                                                        .addProperty("fechaCarga", new StringSchema().format("date-time").example("2025-11-29T00:06:57.260Z"))
                                                        .addProperty("fechaUltimaModificacion", new StringSchema().format("date-time").example("2025-11-29T00:06:57.260Z"))
                                                        .addProperty("origen", new StringSchema().example("CARGA_MANUAL"))
                                                        .addProperty("contenidoTexto", new StringSchema().example("string"))
                                                        .addProperty("contenidoMultimedia", new ArraySchema()
                                                                .items(new ObjectSchema()
                                                                        .addProperty("id", new IntegerSchema().example(0))
                                                                        .addProperty("url", new StringSchema().example("string"))
                                                                )
                                                        )
                                                        .addProperty("anonimato", new BooleanSchema().example(true))
                                                        .addProperty("autor", new ObjectSchema()
                                                                .addProperty("id", new IntegerSchema().example(0))
                                                                .addProperty("esAdministrador", new BooleanSchema().example(true))
                                                                .addProperty("identidad", new ObjectSchema()
                                                                        .addProperty("nombre", new StringSchema().example("string"))
                                                                        .addProperty("apellido", new StringSchema().example("string"))
                                                                        .addProperty("fechaNacimiento", new StringSchema().format("date").example("2025-11-29"))
                                                                )
                                                                .addProperty("mail", new StringSchema().example("string"))
                                                        )
                                                        .addProperty("etiquetas", new ArraySchema()
                                                                .items(new ObjectSchema()
                                                                        .addProperty("nombre", new StringSchema().example("string"))
                                                                )
                                                        )
                                                )
                                        )
                                        .addProperty("number", new IntegerSchema().example(0))
                                        .addProperty("numberOfElements", new IntegerSchema().example(0))
                                        .addProperty("pageable", new ObjectSchema()
                                                .addProperty("offset", new IntegerSchema().example(0))
                                                .addProperty("pageNumber", new IntegerSchema().example(0))
                                                .addProperty("pageSize", new IntegerSchema().example(0))
                                                .addProperty("sort", new ObjectSchema()
                                                        .addProperty("empty", new BooleanSchema().example(true))
                                                        .addProperty("sorted", new BooleanSchema().example(true))
                                                        .addProperty("unsorted", new BooleanSchema().example(true))
                                                )
                                                .addProperty("unpaged", new BooleanSchema().example(true))
                                                .addProperty("paged", new BooleanSchema().example(true))
                                        )
                                        .addProperty("sort", new ObjectSchema()
                                                .addProperty("empty", new BooleanSchema().example(true))
                                                .addProperty("sorted", new BooleanSchema().example(true))
                                                .addProperty("unsorted", new BooleanSchema().example(true))
                                        )
                                        .addProperty("empty", new BooleanSchema().example(true))
                        )
                ));

        paths.addPathItem("/apiPublica/hechos", new PathItem()
                .get(new Operation()
                        .tags(List.of("hecho-controller"))
                        .summary("Obtener todos los hechos")
                        .description("Devuelve la lista completa de hechos, usando paginacion para limitar el tamaño de las respuestas y utilizando los filtros especificados.")
                        .addParametersItem(new Parameter()
                                .name("categoria")
                                .in("query")
                                .required(false)
                                .schema(new StringSchema())
                                .description("Filtra por categoría")
                        )
                        .addParametersItem(new Parameter()
                                .name("fechaReporteDesde")
                                .in("query")
                                .required(false)
                                .schema(new StringSchema().format("date"))
                                .description("Filtra por fecha de reporte desde")
                        )
                        .addParametersItem(new Parameter()
                                .name("fechaReporteHasta")
                                .in("query")
                                .required(false)
                                .schema(new StringSchema().format("date"))
                                .description("Filtra por fecha de reporte hasta")
                        )
                        .addParametersItem(new Parameter()
                                .name("fechaAcontecimientoDesde")
                                .in("query")
                                .required(false)
                                .schema(new StringSchema().format("date-time"))
                                .description("Filtra por fecha de acontecimiento desde")
                        )
                        .addParametersItem(new Parameter()
                                .name("fechaAcontecimientoHasta")
                                .in("query")
                                .required(false)
                                .schema(new StringSchema().format("date-time"))
                                .description("Filtra por fecha de acontecimiento hasta")
                        )
                        .addParametersItem(new Parameter()
                                .name("latitud")
                                .in("query")
                                .required(false)
                                .schema(new NumberSchema().format("double"))
                                .description("Filtra por latitud")
                        )
                        .addParametersItem(new Parameter()
                                .name("longitud")
                                .in("query")
                                .required(false)
                                .schema(new NumberSchema().format("double"))
                                .description("Filtra por longitud")
                        )
                        .addParametersItem(new Parameter()
                                .name("radio")
                                .in("query")
                                .required(false)
                                .schema(new NumberSchema().format("double"))
                                .description("Filtra por radio")
                        )
                        .addParametersItem(new Parameter()
                                .name("search")
                                .in("query")
                                .required(false)
                                .schema(new StringSchema())
                                .description("Término de búsqueda")
                        )
                        .addParametersItem(new Parameter()
                                .name("page")
                                .in("query")
                                .required(false)
                                .schema(new IntegerSchema().example(0))
                                .description("Número de página")
                        )
                        .addParametersItem(new Parameter()
                                .name("size")
                                .in("query")
                                .required(false)
                                .schema(new IntegerSchema().example(100))
                                .description("Tamaño de página")
                        )
                        .responses(new ApiResponses()
                                .addApiResponse("200", paginatedHechosResponse)
                        )
                )
        );

        paths.addPathItem("/apiPublica/hechos/{id}", new PathItem()
                .get(new Operation()
                        .tags(List.of("hecho-controller"))
                        .summary("Obtener hecho por ID")
                        .description("Devuelve un hecho específico según su ID")
                        .addParametersItem(new Parameter()
                                .name("id")
                                .in("path")
                                .required(true)
                                .schema(new IntegerSchema())
                                .description("ID del hecho")
                        )
                        .responses(new ApiResponses()
                                .addApiResponse("200", new ApiResponse()
                                        .description("OK")
                                        .content(new Content().addMediaType("application/json",
                                                new MediaType().schema(
                                                        new ArraySchema()
                                                                .items(new ObjectSchema()
                                                                        .addProperty("id", new StringSchema().example("string"))
                                                                        .addProperty("titulo", new StringSchema().example("string"))
                                                                        .addProperty("descripcion", new StringSchema().example("string"))
                                                                        .addProperty("categoria", new ObjectSchema()
                                                                                .addProperty("id", new IntegerSchema().example(0))
                                                                                .addProperty("nombre", new StringSchema().example("string"))
                                                                        )
                                                                        .addProperty("ubicacion", new ObjectSchema()
                                                                                .addProperty("latitud", new NumberSchema().example(0))
                                                                                .addProperty("longitud", new NumberSchema().example(0))
                                                                        )
                                                                        .addProperty("fechaAcontecimiento", new StringSchema().format("date-time").example("2025-11-29T00:04:33.303Z"))
                                                                        .addProperty("fechaCarga", new StringSchema().format("date-time").example("2025-11-29T00:04:33.303Z"))
                                                                        .addProperty("fechaUltimaModificacion", new StringSchema().format("date-time").example("2025-11-29T00:04:33.303Z"))
                                                                        .addProperty("origen", new StringSchema().example("CARGA_MANUAL"))
                                                                        .addProperty("contenidoTexto", new StringSchema().example("string"))
                                                                        .addProperty("contenidoMultimedia", new ArraySchema()
                                                                                .items(new ObjectSchema()
                                                                                        .addProperty("id", new IntegerSchema().example(0))
                                                                                        .addProperty("url", new StringSchema().example("string"))
                                                                                )
                                                                        )
                                                                        .addProperty("anonimato", new BooleanSchema().example(true))
                                                                        .addProperty("autor", new ObjectSchema()
                                                                                .addProperty("id", new IntegerSchema().example(0))
                                                                                .addProperty("esAdministrador", new BooleanSchema().example(true))
                                                                                .addProperty("identidad", new ObjectSchema()
                                                                                        .addProperty("nombre", new StringSchema().example("string"))
                                                                                        .addProperty("apellido", new StringSchema().example("string"))
                                                                                        .addProperty("fechaNacimiento", new StringSchema().format("date").example("2025-11-29"))
                                                                                )
                                                                                .addProperty("mail", new StringSchema().example("string"))
                                                                        )
                                                                        .addProperty("etiquetas", new ArraySchema()
                                                                                .items(new ObjectSchema()
                                                                                        .addProperty("nombre", new StringSchema().example("string"))
                                                                                )
                                                                        )
                                                                )
                                                )
                                        ))
                                )
                        )
                )
        );

        paths.addPathItem("/apiPublica/hechos/index", new PathItem()
                .get(new Operation()
                        .tags(List.of("hecho-controller"))
                        .summary("Autocompletar hechos / index")
                        .description("Devuelve datos para autocompletar las recomendaciones de busqueda de hechos")
                        .responses(new ApiResponses()
                                .addApiResponse("200", new ApiResponse()
                                        .description("OK")
                                        .content(new Content().addMediaType("application/json",
                                                new MediaType().schema(
                                                        new ArraySchema()
                                                                .items(new StringSchema().example("Titulo de hecho de prueba"))
                                                )
                                        ))
                                )
                        )
                )
        );

        paths.addPathItem("/apiPublica/colecciones", new PathItem()
                .get(new Operation()
                        .tags(List.of("coleccion-controller"))
                        .summary("Mostrar todas las colecciones")
                        .description("Devuelve la lista completa de colecciones con paginación")
                        .responses(new ApiResponses()
                                .addApiResponse("200", new ApiResponse()
                                        .description("OK")
                                        .content(new Content().addMediaType("application/json",
                                                new MediaType().schema(
                                                        new ObjectSchema()
                                                                .addProperty("totalElements", new IntegerSchema().example(0))
                                                                .addProperty("totalPages", new IntegerSchema().example(0))
                                                                .addProperty("first", new BooleanSchema().example(true))
                                                                .addProperty("last", new BooleanSchema().example(true))
                                                                .addProperty("size", new IntegerSchema().example(0))
                                                                .addProperty("number", new IntegerSchema().example(0))
                                                                .addProperty("numberOfElements", new IntegerSchema().example(0))
                                                                .addProperty("empty", new BooleanSchema().example(true))
                                                                .addProperty("content", new ArraySchema()
                                                                        .items(new ObjectSchema()
                                                                                .addProperty("id", new StringSchema().example("string"))
                                                                                .addProperty("titulo", new StringSchema().example("string"))
                                                                                .addProperty("descripcion", new StringSchema().example("string"))
                                                                                .addProperty("criteriosDePertenencia", new ArraySchema()
                                                                                        .items(new ObjectSchema()
                                                                                                .addProperty("id", new IntegerSchema().example(0))
                                                                                        )
                                                                                )
                                                                                .addProperty("fuentes", new ArraySchema()
                                                                                        .items(new ObjectSchema()
                                                                                                .addProperty("id", new StringSchema().example("string"))
                                                                                                .addProperty("alias", new StringSchema().example("string"))
                                                                                        )
                                                                                )
                                                                                .addProperty("tipoAlgoritmoConsenso", new StringSchema().example("IRRESTRICTO"))
                                                                        )
                                                                )
                                                                .addProperty("pageable", new ObjectSchema()
                                                                        .addProperty("offset", new IntegerSchema().example(0))
                                                                        .addProperty("pageNumber", new IntegerSchema().example(0))
                                                                        .addProperty("pageSize", new IntegerSchema().example(0))
                                                                        .addProperty("sort", new ObjectSchema()
                                                                                .addProperty("empty", new BooleanSchema().example(true))
                                                                                .addProperty("sorted", new BooleanSchema().example(true))
                                                                                .addProperty("unsorted", new BooleanSchema().example(true))
                                                                        )
                                                                        .addProperty("unpaged", new BooleanSchema().example(true))
                                                                        .addProperty("paged", new BooleanSchema().example(true))
                                                                )
                                                                .addProperty("sort", new ObjectSchema()
                                                                        .addProperty("empty", new BooleanSchema().example(true))
                                                                        .addProperty("sorted", new BooleanSchema().example(true))
                                                                        .addProperty("unsorted", new BooleanSchema().example(true))
                                                                )
                                                )
                                        ))
                                )
                        )
                )
        );

        paths.addPathItem("/apiPublica/colecciones/{id}", new PathItem()
                .get(new Operation()
                        .tags(List.of("coleccion-controller"))
                        .summary("Mostrar colección por ID")
                        .description("Devuelve una colección específica según su ID")
                        .addParametersItem(new Parameter()
                                .name("id")
                                .in("path")
                                .required(true)
                                .schema(new IntegerSchema())
                                .description("ID de la colección")
                        )
                        .responses(new ApiResponses()
                                .addApiResponse("200", new ApiResponse()
                                        .description("OK")
                                        .content(new Content().addMediaType("application/json",
                                                new MediaType().schema(
                                                        new ObjectSchema()
                                                                .addProperty("id", new StringSchema().example("string"))
                                                                .addProperty("titulo", new StringSchema().example("string"))
                                                                .addProperty("descripcion", new StringSchema().example("string"))
                                                                .addProperty("criteriosDePertenencia", new ArraySchema()
                                                                        .items(new ObjectSchema()
                                                                                .addProperty("id", new IntegerSchema().example(0))
                                                                        )
                                                                )
                                                                .addProperty("fuentes", new ArraySchema()
                                                                        .items(new ObjectSchema()
                                                                                .addProperty("id", new StringSchema().example("string"))
                                                                                .addProperty("alias", new StringSchema().example("string"))
                                                                        )
                                                                )
                                                                .addProperty("tipoAlgoritmoConsenso", new StringSchema().example("IRRESTRICTO"))
                                                )
                                        ))
                                )
                        )
                )
        );
        paths.addPathItem("/apiPublica/colecciones/{id}/hechosIrrestrictos", new PathItem()
                .get(new Operation()
                        .tags(List.of("coleccion-controller"))
                        .summary("Mostrar hechos irrestrictos de la colección")
                        .description("Devuelve los hechos irrestrictos asociados a una colección")
                        .addParametersItem(new Parameter()
                                .name("id")
                                .in("path")
                                .required(true)
                                .schema(new IntegerSchema())
                                .description("ID de la colección")
                        )
                        .addParametersItem(new Parameter()
                                .name("categoria")
                                .in("query")
                                .required(false)
                                .schema(new StringSchema())
                                .description("Filtra por categoría")
                        )
                        .addParametersItem(new Parameter()
                                .name("fechaReporteDesde")
                                .in("query")
                                .required(false)
                                .schema(new StringSchema().format("date"))
                                .description("Filtra por fecha de reporte desde")
                        )
                        .addParametersItem(new Parameter()
                                .name("fechaReporteHasta")
                                .in("query")
                                .required(false)
                                .schema(new StringSchema().format("date"))
                                .description("Filtra por fecha de reporte hasta")
                        )
                        .addParametersItem(new Parameter()
                                .name("fechaAcontecimientoDesde")
                                .in("query")
                                .required(false)
                                .schema(new StringSchema().format("date-time"))
                                .description("Filtra por fecha de acontecimiento desde")
                        )
                        .addParametersItem(new Parameter()
                                .name("fechaAcontecimientoHasta")
                                .in("query")
                                .required(false)
                                .schema(new StringSchema().format("date-time"))
                                .description("Filtra por fecha de acontecimiento hasta")
                        )
                        .addParametersItem(new Parameter()
                                .name("latitud")
                                .in("query")
                                .required(false)
                                .schema(new NumberSchema().format("double"))
                                .description("Filtra por latitud")
                        )
                        .addParametersItem(new Parameter()
                                .name("longitud")
                                .in("query")
                                .required(false)
                                .schema(new NumberSchema().format("double"))
                                .description("Filtra por longitud")
                        )
                        .addParametersItem(new Parameter()
                                .name("radio")
                                .in("query")
                                .required(false)
                                .schema(new NumberSchema().format("double"))
                                .description("Filtra por radio")
                        )
                        .addParametersItem(new Parameter()
                                .name("search")
                                .in("query")
                                .required(false)
                                .schema(new StringSchema())
                                .description("Término de búsqueda")
                        )
                        .addParametersItem(new Parameter()
                                .name("page")
                                .in("query")
                                .required(false)
                                .schema(new IntegerSchema().example(0))
                                .description("Número de página")
                        )
                        .addParametersItem(new Parameter()
                                .name("size")
                                .in("query")
                                .required(false)
                                .schema(new IntegerSchema().example(100))
                                .description("Tamaño de página")
                        )
                        .responses(new ApiResponses()
                                .addApiResponse("200", paginatedHechosResponse)
                        )
                )
        );

        paths.addPathItem("/apiPublica/colecciones/{id}/hechosCurados", new PathItem()
                .get(new Operation()
                        .tags(List.of("coleccion-controller"))
                        .summary("Mostrar hechos curados de la colección")
                        .description("Devuelve los hechos curados asociados a una colección")
                        .addParametersItem(new Parameter()
                                .name("id")
                                .in("path")
                                .required(true)
                                .schema(new IntegerSchema())
                                .description("ID de la colección")
                        )
                        .addParametersItem(new Parameter()
                                .name("categoria")
                                .in("query")
                                .required(false)
                                .schema(new StringSchema())
                                .description("Filtra por categoría")
                        )
                        .addParametersItem(new Parameter()
                                .name("fechaReporteDesde")
                                .in("query")
                                .required(false)
                                .schema(new StringSchema().format("date"))
                                .description("Filtra por fecha de reporte desde")
                        )
                        .addParametersItem(new Parameter()
                                .name("fechaReporteHasta")
                                .in("query")
                                .required(false)
                                .schema(new StringSchema().format("date"))
                                .description("Filtra por fecha de reporte hasta")
                        )
                        .addParametersItem(new Parameter()
                                .name("fechaAcontecimientoDesde")
                                .in("query")
                                .required(false)
                                .schema(new StringSchema().format("date-time"))
                                .description("Filtra por fecha de acontecimiento desde")
                        )
                        .addParametersItem(new Parameter()
                                .name("fechaAcontecimientoHasta")
                                .in("query")
                                .required(false)
                                .schema(new StringSchema().format("date-time"))
                                .description("Filtra por fecha de acontecimiento hasta")
                        )
                        .addParametersItem(new Parameter()
                                .name("latitud")
                                .in("query")
                                .required(false)
                                .schema(new NumberSchema().format("double"))
                                .description("Filtra por latitud")
                        )
                        .addParametersItem(new Parameter()
                                .name("longitud")
                                .in("query")
                                .required(false)
                                .schema(new NumberSchema().format("double"))
                                .description("Filtra por longitud")
                        )
                        .addParametersItem(new Parameter()
                                .name("radio")
                                .in("query")
                                .required(false)
                                .schema(new NumberSchema().format("double"))
                                .description("Filtra por radio")
                        )
                        .addParametersItem(new Parameter()
                                .name("search")
                                .in("query")
                                .required(false)
                                .schema(new StringSchema())
                                .description("Término de búsqueda")
                        )
                        .addParametersItem(new Parameter()
                                .name("page")
                                .in("query")
                                .required(false)
                                .schema(new IntegerSchema().example(0))
                                .description("Número de página")
                        )
                        .addParametersItem(new Parameter()
                                .name("size")
                                .in("query")
                                .required(false)
                                .schema(new IntegerSchema().example(100))
                                .description("Tamaño de página")
                        )
                        .responses(new ApiResponses()
                                .addApiResponse("200", paginatedHechosResponse
                                )
                        )
                )
        );

        paths.addPathItem("/apiPublica/colecciones/index", new PathItem()
                .get(new Operation()
                        .tags(List.of("coleccion-controller"))
                        .summary("Autocompletar colecciones / índice")
                        .description("Devuelve datos para autocompletar en las busquedas de coleccoines")
                        .responses(new ApiResponses()
                                .addApiResponse("200", new ApiResponse()
                                        .description("OK")
                                        .content(new Content().addMediaType("application/json",
                                                new MediaType().schema(
                                                        new ArraySchema()
                                                                .items(new StringSchema().example("Titulo de hecho de prueba"))
                                                )
                                        ))
                                )
                        )
                )
        );











        return new OpenAPI()
                .info(new io.swagger.v3.oas.models.info.Info()
                        .title("API Pública de Metamapa")
                        .version("1.0")
                        .description("""
                                ● Consulta de hechos dentro de una colección.
                                ● Generar una solicitud de eliminación a un hecho.
                                ● Navegación filtrada sobre una colección.
                                ● Navegación curada o irrestricta sobre una colección.
                                ● Reportar un hecho.""")
                        .contact(new io.swagger.v3.oas.models.info.Contact()
                                .name("DDS K3002 Grupo 2")
                                .email("aherzkovich@frba.utn.edu.ar"))
                        .license(new io.swagger.v3.oas.models.info.License()
                                .name("MIT")
                                .url("https://opensource.org/licenses/MIT"))
                )
                .servers(List.of(
                        new io.swagger.v3.oas.models.servers.Server()
                                .url("http://localhost:8085")
                )).paths(paths);
    }
}