package aplicacion.config;
import io.swagger.v3.oas.models.parameters.Parameter;
import io.swagger.v3.oas.models.parameters.RequestBody;
import io.swagger.v3.oas.models.responses.ApiResponses;
import io.swagger.v3.oas.models.media.*;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import io.swagger.v3.oas.models.*;
import io.swagger.v3.oas.models.Operation;
import io.swagger.v3.oas.models.media.StringSchema;
import io.swagger.v3.oas.models.responses.ApiResponse;


import java.util.List;
import java.util.Map;

@Configuration
public class SwaggerConfig {
    // Se puede usar para borrar todos los paths no manuales
    /*
    @Bean
    public GroupedOpenApi manualApi() {
        return GroupedOpenApi.builder()
                .group("manual")
                .packagesToScan("")
                .build();
    }*/
    @Bean
    public OpenAPI customOpenAPI() {

        Paths paths = new Paths();
        paths.addPathItem("/apiPublica/solicitudes", new PathItem()
                .post(new Operation()
                        .tags(List.of("solicitud-controller"))
                        .summary("Crear una nueva solicitud")
                        .description("Crea una solicitud con solicitanteId, hechoId y motivo")
                        .requestBody(new io.swagger.v3.oas.models.parameters.RequestBody()
                                .required(true)
                                .content(new Content()
                                        .addMediaType("application/json",
                                                new MediaType()
                                                        .schema(new ObjectSchema()
                                                                .addProperty("solicitanteId", new IntegerSchema())
                                                                .addProperty("hechoId", new StringSchema())
                                                                .addProperty("motivo", new StringSchema())
                                                                .example(Map.of(
                                                                        "solicitanteId", 1,
                                                                        "hechoId", "hecho-123",
                                                                        "motivo", "En los anales de nuestro reino, todo acto que busque la supresión de un registro o la eliminación de un documento se ha de considerar con sumo cuidado, pues cada acción deja su impronta en el vasto libro de la memoria del reino. No basta con un mero capricho o la impaciencia del instante; es menester que quien solicita tal acción exponga con claridad y sobrada razón los fundamentos que la sustentan, describiendo los hechos, las causas y las consecuencias, de modo que los guardianes de la memoria puedan ponderar y juzgar con justicia la petición. Por mandato antiguo, se requiere que la justificación contenga no menos de quinientos caracteres, para que quede patente que la solicitud está debidamente reflexionada y fundamentada, asegurando así que la verdad y la equidad prevalezcan, y evitando que la sombra de la negligencia o de la precipitación borre de manera irremisible aquello que podría tener valor para generaciones futuras, pues la historia enseña que cada omisión mal fundamentada puede traer penurias y desdén sobre los que gobiernan y preservan el archivo del reino."
                                                                ))
                                                        )
                                        )
                                )
                        )
                        .responses(new ApiResponses()
                                .addApiResponse("200", new ApiResponse()
                                        .description("OK")
                                        .content(new Content()
                                                .addMediaType("application/json",
                                                        new MediaType()
                                                                .schema(new ObjectSchema()
                                                                        .addProperty("id", new IntegerSchema().example(0))
                                                                        .addProperty("solicitanteId", new IntegerSchema().example(0))
                                                                        .addProperty("hechoId", new StringSchema().example("string"))
                                                                        .addProperty("motivo", new StringSchema().example("string"))
                                                                        .addProperty("estado", new ObjectSchema()
                                                                                .addProperty("estado", new StringSchema().example("string"))
                                                                        )
                                                                        .addProperty("fechaSubida", new StringSchema().example("2025-11-28T23:10:19.848Z"))
                                                                )
                                                )
                                        )
                                )
                        )
                ));
        paths.addPathItem("/apiPublica/contribuyentes", new PathItem()
                .get(new Operation()
                        .operationId("obtenerContribuyentes")
                        .tags(List.of("contribuyente-controller"))
                        .summary("Obtener contribuyentes")
                        .description("Devuelve la lista de todos los contribuyentes, opcionalmente filtrando por mail. Redirige al agregador para obtener los datos.")
                        .addParametersItem(new Parameter()
                                .name("mail")
                                .in("query")
                                .description("Filtra contribuyentes por dirección de correo electrónico (búsqueda exacta)")
                                .required(false)
                                .schema(new StringSchema())
                        )
                        .responses(new ApiResponses()
                                .addApiResponse("200", new ApiResponse()
                                        .description("OK")
                                        .content(new Content().addMediaType("application/json",
                                                new MediaType().schema(
                                                        new ArraySchema()
                                                                .items(new ObjectSchema()
                                                                        .addProperty("id", new IntegerSchema().example(1))
                                                                        .addProperty("esAdministrador", new BooleanSchema().example(false))
                                                                        .addProperty("identidad", new ObjectSchema()
                                                                                .addProperty("nombre", new StringSchema().example("Juan"))
                                                                                .addProperty("apellido", new StringSchema().example("Pérez"))
                                                                                .addProperty("fechaNacimiento", new StringSchema().format("date").example("1990-05-15"))
                                                                        )
                                                                        .addProperty("mail", new StringSchema().example("juan.perez@example.com"))
                                                                )
                                                )
                                        ))
                                )
                        )
                )
                .post(new Operation()
                        .operationId("crearContribuyente")
                        .tags(List.of("contribuyente-controller"))
                        .summary("Crear contribuyente")
                        .description("Crea un nuevo contribuyente y lo registra tanto en fuente dinámica como en agregador")
                        .requestBody(new RequestBody()
                                .required(true)
                                .content(new Content().addMediaType("application/json",
                                        new MediaType().schema(new ObjectSchema()
                                                .addProperty("nombre", new StringSchema())
                                                .addProperty("apellido", new StringSchema())
                                                .addProperty("fechaNacimiento", new StringSchema().format("date"))
                                                .addProperty("mail", new StringSchema())
                                                .example(Map.of(
                                                        "nombre", "Juan",
                                                        "apellido", "Pérez",
                                                        "fechaNacimiento", "1990-05-15",
                                                        "mail", "juan.perez@example.com"
                                                ))
                                        )
                                ))
                        )
                        .responses(new ApiResponses()
                                .addApiResponse("200", new ApiResponse()
                                        .description("Contribuyente creado exitosamente")
                                        .content(new Content().addMediaType("application/json",
                                                new MediaType().schema(new ObjectSchema()
                                                        .addProperty("id", new IntegerSchema().example(1))
                                                        .addProperty("esAdministrador", new BooleanSchema().example(false))
                                                        .addProperty("identidad", new ObjectSchema()
                                                                .addProperty("nombre", new StringSchema().example("Juan"))
                                                                .addProperty("apellido", new StringSchema().example("Pérez"))
                                                                .addProperty("fechaNacimiento", new StringSchema().format("date").example("1990-05-15"))
                                                        )
                                                        .addProperty("mail", new StringSchema().example("juan.perez@example.com"))
                                                )
                                        ))
                                )
                        )
                )
        );

        paths.addPathItem("/apiPublica/contribuyentes/{id}/identidad", new PathItem()
                .patch(new Operation()
                        .tags(List.of("contribuyente-controller"))
                        .summary("Modificar identidad de un contribuyente")
                        .description("Actualiza la información de identidad de un contribuyente existente")
                        .addParametersItem(new Parameter()
                                .name("id")
                                .in("path")
                                .required(true)
                                .schema(new UUIDSchema())
                                .description("ID del contribuyente")
                        )
                        .requestBody(new RequestBody()
                                .required(true)
                                .content(new Content().addMediaType("application/json",
                                        new MediaType().schema(new ObjectSchema()
                                                .addProperty("nombre", new StringSchema())
                                                .addProperty("apellido", new StringSchema())
                                                .addProperty("fechaNacimiento", new StringSchema().format("date"))
                                                .example(Map.of(
                                                        "nombre", "Agustin",
                                                        "apellido", "Herzkovich",
                                                        "fechaNacimiento", "2005-11-29"
                                                ))
                                        )
                                ))
                        )
                        .responses(new ApiResponses()
                                .addApiResponse("200", new ApiResponse().description("Identidad actualizada"))
                        )
                )
        );

        paths.addPathItem("/apiPublica/contribuyentes/{id}/hechos", new PathItem()
                .get(new Operation()
                        .tags(List.of("contribuyente-controller"))
                        .summary("Obtener hechos de un contribuyente")
                        .description("Devuelve la lista de hechos asociados a un contribuyente")
                        .addParametersItem(new Parameter()
                                .name("id")
                                .in("path")
                                .required(true)
                                .schema(new IntegerSchema())
                                .description("ID del contribuyente")
                        )
                        .responses(new ApiResponses()
                                .addApiResponse("200", new ApiResponse()
                                        .description("OK")
                                        .content(new Content().addMediaType("application/json",
                                                new MediaType().schema(
                                                        new ArraySchema()
                                                                .items(new ObjectSchema()
                                                                        .addProperty("id", new StringSchema().example("string"))
                                                                        .addProperty("titulo", new StringSchema().example("string"))
                                                                        .addProperty("descripcion", new StringSchema().example("string"))
                                                                        .addProperty("categoria", new ObjectSchema()
                                                                                .addProperty("id", new IntegerSchema().example(0))
                                                                                .addProperty("nombre", new StringSchema().example("string"))
                                                                        )
                                                                        .addProperty("ubicacion", new ObjectSchema()
                                                                                .addProperty("latitud", new NumberSchema().example(0))
                                                                                .addProperty("longitud", new NumberSchema().example(0))
                                                                        )
                                                                        .addProperty("fechaAcontecimiento", new StringSchema().format("date-time").example("2025-11-29T00:04:33.303Z"))
                                                                        .addProperty("fechaCarga", new StringSchema().format("date-time").example("2025-11-29T00:04:33.303Z"))
                                                                        .addProperty("fechaUltimaModificacion", new StringSchema().format("date-time").example("2025-11-29T00:04:33.303Z"))
                                                                        .addProperty("origen", new StringSchema().example("CARGA_MANUAL"))
                                                                        .addProperty("contenidoTexto", new StringSchema().example("string"))
                                                                        .addProperty("contenidoMultimedia", new ArraySchema()
                                                                                .items(new ObjectSchema()
                                                                                        .addProperty("id", new IntegerSchema().example(0))
                                                                                        .addProperty("url", new StringSchema().example("string"))
                                                                                )
                                                                        )
                                                                        .addProperty("anonimato", new BooleanSchema().example(true))
                                                                        .addProperty("autor", new ObjectSchema()
                                                                                .addProperty("id", new IntegerSchema().example(0))
                                                                                .addProperty("esAdministrador", new BooleanSchema().example(true))
                                                                                .addProperty("identidad", new ObjectSchema()
                                                                                        .addProperty("nombre", new StringSchema().example("string"))
                                                                                        .addProperty("apellido", new StringSchema().example("string"))
                                                                                        .addProperty("fechaNacimiento", new StringSchema().format("date").example("2025-11-29"))
                                                                                )
                                                                                .addProperty("mail", new StringSchema().example("string"))
                                                                        )
                                                                        .addProperty("etiquetas", new ArraySchema()
                                                                                .items(new ObjectSchema()
                                                                                        .addProperty("nombre", new StringSchema().example("string"))
                                                                                )
                                                                        )
                                                                )
                                                )
                                        ))
                                )
                        )
                )
        );
// ApiResponse reutilizable para lista paginada de hechos
        ApiResponse paginatedHechosResponse = new ApiResponse()
                .description("Lista paginada de hechos")
                .content(new Content().addMediaType("application/json",
                        new MediaType().schema(
                                new ObjectSchema()
                                        .addProperty("totalElements", new IntegerSchema().example(0))
                                        .addProperty("totalPages", new IntegerSchema().example(0))
                                        .addProperty("first", new BooleanSchema().example(true))
                                        .addProperty("last", new BooleanSchema().example(true))
                                        .addProperty("size", new IntegerSchema().example(0))
                                        .addProperty("content", new ArraySchema()
                                                .items(new ObjectSchema()
                                                        .addProperty("id", new StringSchema().example("string"))
                                                        .addProperty("titulo", new StringSchema().example("string"))
                                                        .addProperty("descripcion", new StringSchema().example("string"))
                                                        .addProperty("categoria", new ObjectSchema()
                                                                .addProperty("id", new IntegerSchema().example(0))
                                                                .addProperty("nombre", new StringSchema().example("string"))
                                                        )
                                                        .addProperty("ubicacion", new ObjectSchema()
                                                                .addProperty("latitud", new NumberSchema().example(0))
                                                                .addProperty("longitud", new NumberSchema().example(0))
                                                        )
                                                        .addProperty("fechaAcontecimiento", new StringSchema().format("date-time").example("2025-11-29T00:06:57.260Z"))
                                                        .addProperty("fechaCarga", new StringSchema().format("date-time").example("2025-11-29T00:06:57.260Z"))
                                                        .addProperty("fechaUltimaModificacion", new StringSchema().format("date-time").example("2025-11-29T00:06:57.260Z"))
                                                        .addProperty("origen", new StringSchema().example("CARGA_MANUAL"))
                                                        .addProperty("contenidoTexto", new StringSchema().example("string"))
                                                        .addProperty("contenidoMultimedia", new ArraySchema()
                                                                .items(new ObjectSchema()
                                                                        .addProperty("id", new IntegerSchema().example(0))
                                                                        .addProperty("url", new StringSchema().example("string"))
                                                                )
                                                        )
                                                        .addProperty("anonimato", new BooleanSchema().example(true))
                                                        .addProperty("autor", new ObjectSchema()
                                                                .addProperty("id", new IntegerSchema().example(0))
                                                                .addProperty("esAdministrador", new BooleanSchema().example(true))
                                                                .addProperty("identidad", new ObjectSchema()
                                                                        .addProperty("nombre", new StringSchema().example("string"))
                                                                        .addProperty("apellido", new StringSchema().example("string"))
                                                                        .addProperty("fechaNacimiento", new StringSchema().format("date").example("2025-11-29"))
                                                                )
                                                                .addProperty("mail", new StringSchema().example("string"))
                                                        )
                                                        .addProperty("etiquetas", new ArraySchema()
                                                                .items(new ObjectSchema()
                                                                        .addProperty("nombre", new StringSchema().example("string"))
                                                                )
                                                        )
                                                )
                                        )
                                        .addProperty("number", new IntegerSchema().example(0))
                                        .addProperty("numberOfElements", new IntegerSchema().example(0))
                                        .addProperty("pageable", new ObjectSchema()
                                                .addProperty("offset", new IntegerSchema().example(0))
                                                .addProperty("pageNumber", new IntegerSchema().example(0))
                                                .addProperty("pageSize", new IntegerSchema().example(0))
                                                .addProperty("sort", new ObjectSchema()
                                                        .addProperty("empty", new BooleanSchema().example(true))
                                                        .addProperty("sorted", new BooleanSchema().example(true))
                                                        .addProperty("unsorted", new BooleanSchema().example(true))
                                                )
                                                .addProperty("unpaged", new BooleanSchema().example(true))
                                                .addProperty("paged", new BooleanSchema().example(true))
                                        )
                                        .addProperty("sort", new ObjectSchema()
                                                .addProperty("empty", new BooleanSchema().example(true))
                                                .addProperty("sorted", new BooleanSchema().example(true))
                                                .addProperty("unsorted", new BooleanSchema().example(true))
                                        )
                                        .addProperty("empty", new BooleanSchema().example(true))
                        )
                ));

        paths.addPathItem("/apiPublica/hechos", new PathItem()
                .get(new Operation()
                        .tags(List.of("hecho-controller"))
                        .summary("Obtener todos los hechos")
                        .description("Devuelve la lista completa de hechos usando paginación y filtros. Redirige al agregador y utiliza GraphQL para consultar los datos. Soporta filtros por categoría, fechas, ubicación geográfica y búsqueda por texto libre.")
                        .addParametersItem(new Parameter()
                                .name("categoria")
                                .in("query")
                                .required(false)
                                .schema(new StringSchema())
                                .description("Filtra por categoría del hecho (ej: Incendio, Inundación)")
                        )
                        .addParametersItem(new Parameter()
                                .name("fechaReporteDesde")
                                .in("query")
                                .required(false)
                                .schema(new StringSchema().format("date-time"))
                                .description("Filtra por fecha de reporte desde (formato ISO-8601)")
                        )
                        .addParametersItem(new Parameter()
                                .name("fechaReporteHasta")
                                .in("query")
                                .required(false)
                                .schema(new StringSchema().format("date-time"))
                                .description("Filtra por fecha de reporte hasta (formato ISO-8601)")
                        )
                        .addParametersItem(new Parameter()
                                .name("fechaAcontecimientoDesde")
                                .in("query")
                                .required(false)
                                .schema(new StringSchema().format("date-time"))
                                .description("Filtra por fecha de acontecimiento desde (formato ISO-8601)")
                        )
                        .addParametersItem(new Parameter()
                                .name("fechaAcontecimientoHasta")
                                .in("query")
                                .required(false)
                                .schema(new StringSchema().format("date-time"))
                                .description("Filtra por fecha de acontecimiento hasta (formato ISO-8601)")
                        )
                        .addParametersItem(new Parameter()
                                .name("latitud")
                                .in("query")
                                .required(false)
                                .schema(new NumberSchema().format("double"))
                                .description("Latitud del centro de búsqueda geográfica (requiere longitud y radio)")
                        )
                        .addParametersItem(new Parameter()
                                .name("longitud")
                                .in("query")
                                .required(false)
                                .schema(new NumberSchema().format("double"))
                                .description("Longitud del centro de búsqueda geográfica (requiere latitud y radio)")
                        )
                        .addParametersItem(new Parameter()
                                .name("radio")
                                .in("query")
                                .required(false)
                                .schema(new NumberSchema().format("double"))
                                .description("Radio en kilómetros para búsqueda geográfica (requiere latitud y longitud)")
                        )
                        .addParametersItem(new Parameter()
                                .name("search")
                                .in("query")
                                .required(false)
                                .schema(new StringSchema())
                                .description("Búsqueda por texto libre en título y descripción del hecho")
                        )
                        .addParametersItem(new Parameter()
                                .name("page")
                                .in("query")
                                .required(false)
                                .schema(new IntegerSchema().example(0))
                                .description("Número de página (comienza en 0)")
                        )
                        .addParametersItem(new Parameter()
                                .name("size")
                                .in("query")
                                .required(false)
                                .schema(new IntegerSchema().example(100))
                                .description("Tamaño de página (cantidad de elementos por página)")
                        )
                        .responses(new ApiResponses()
                                .addApiResponse("200", paginatedHechosResponse)
                        )
                )
                .post(new Operation()
                        .tags(List.of("hecho-controller"))
                        .summary("Agregar un nuevo hecho")
                        .description("Crea un nuevo hecho como contribuyente. Se envía a fuente dinámica para su procesamiento")
                        .requestBody(new io.swagger.v3.oas.models.parameters.RequestBody()
                                .required(true)
                                .content(new Content()
                                        .addMediaType("application/json",
                                                new MediaType()
                                                        .schema(new ObjectSchema()
                                                                .addProperty("titulo", new StringSchema())
                                                                .addProperty("descripcion", new StringSchema())
                                                                .addProperty("latitud", new NumberSchema().format("double"))
                                                                .addProperty("longitud", new NumberSchema().format("double"))
                                                                .addProperty("categoria", new StringSchema())
                                                                .addProperty("fechaAcontecimiento", new StringSchema().format("date-time"))
                                                                .addProperty("contribuyenteId", new IntegerSchema())
                                                                .example(Map.of(
                                                                        "titulo", "Incendio forestal en Córdoba",
                                                                        "descripcion", "Gran incendio en zona forestal",
                                                                        "latitud", -31.4201,
                                                                        "longitud", -64.1888,
                                                                        "categoria", "Incendio",
                                                                        "fechaAcontecimiento", "2025-12-02T10:00:00Z",
                                                                        "contribuyenteId", 1
                                                                ))
                                                        )
                                        )
                                )
                        )
                        .responses(new ApiResponses()
                                .addApiResponse("200", new ApiResponse()
                                        .description("Hecho creado exitosamente")
                                        .content(new Content()
                                                .addMediaType("application/json",
                                                        new MediaType()
                                                                .schema(new ObjectSchema()
                                                                        .addProperty("id", new StringSchema().example("hecho-123"))
                                                                        .addProperty("titulo", new StringSchema().example("Incendio forestal en Córdoba"))
                                                                        .addProperty("latitud", new NumberSchema().example(-31.4201))
                                                                        .addProperty("longitud", new NumberSchema().example(-64.1888))
                                                                        .addProperty("categoria", new StringSchema().example("Incendio"))
                                                                        .addProperty("fechaCarga", new StringSchema().format("date-time").example("2025-12-02T10:00:00Z"))
                                                                )
                                                )
                                        )
                                )
                        )
                )
        );

        paths.addPathItem("/apiPublica/hechos/{id}", new PathItem()
                .get(new Operation()
                        .tags(List.of("hecho-controller"))
                        .summary("Obtener hecho por ID")
                        .description("Devuelve un hecho específico según su ID. Redirige al agregador para obtener los datos completos del hecho.")
                        .addParametersItem(new Parameter()
                                .name("id")
                                .in("path")
                                .required(true)
                                .schema(new StringSchema())
                                .description("ID del hecho")
                        )
                        .responses(new ApiResponses()
                                .addApiResponse("200", new ApiResponse()
                                        .description("OK")
                                        .content(new Content().addMediaType("application/json",
                                                new MediaType().schema(
                                                        new ObjectSchema()
                                                                .addProperty("id", new StringSchema().example("hecho-123"))
                                                                .addProperty("titulo", new StringSchema().example("Incendio forestal en Córdoba"))
                                                                .addProperty("descripcion", new StringSchema().example("Gran incendio en zona forestal"))
                                                                .addProperty("categoria", new ObjectSchema()
                                                                        .addProperty("id", new IntegerSchema().example(1))
                                                                        .addProperty("nombre", new StringSchema().example("Incendio"))
                                                                )
                                                                .addProperty("ubicacion", new ObjectSchema()
                                                                        .addProperty("latitud", new NumberSchema().example(-31.4201))
                                                                        .addProperty("longitud", new NumberSchema().example(-64.1888))
                                                                )
                                                                .addProperty("fechaAcontecimiento", new StringSchema().format("date-time").example("2025-11-29T00:04:33.303Z"))
                                                                .addProperty("fechaCarga", new StringSchema().format("date-time").example("2025-11-29T00:04:33.303Z"))
                                                                .addProperty("fechaUltimaModificacion", new StringSchema().format("date-time").example("2025-11-29T00:04:33.303Z"))
                                                                .addProperty("origen", new StringSchema().example("CARGA_MANUAL"))
                                                                .addProperty("contenidoTexto", new StringSchema().example("Contenido detallado del hecho"))
                                                                .addProperty("contenidoMultimedia", new ArraySchema()
                                                                        .items(new ObjectSchema()
                                                                                .addProperty("id", new IntegerSchema().example(1))
                                                                                .addProperty("url", new StringSchema().example("https://example.com/imagen.jpg"))
                                                                        )
                                                                )
                                                                .addProperty("anonimato", new BooleanSchema().example(false))
                                                                .addProperty("autor", new ObjectSchema()
                                                                        .addProperty("id", new IntegerSchema().example(1))
                                                                        .addProperty("esAdministrador", new BooleanSchema().example(false))
                                                                        .addProperty("identidad", new ObjectSchema()
                                                                                .addProperty("nombre", new StringSchema().example("Juan"))
                                                                                .addProperty("apellido", new StringSchema().example("Pérez"))
                                                                                .addProperty("fechaNacimiento", new StringSchema().format("date").example("1990-05-15"))
                                                                        )
                                                                        .addProperty("mail", new StringSchema().example("juan.perez@example.com"))
                                                                )
                                                                .addProperty("etiquetas", new ArraySchema()
                                                                        .items(new ObjectSchema()
                                                                                .addProperty("nombre", new StringSchema().example("Urgente"))
                                                                        )
                                                                )
                                                )
                                        ))
                                )
                        )
                )
                .patch(new Operation()
                        .tags(List.of("hecho-controller"))
                        .summary("Editar un hecho existente")
                        .description("Edita un hecho como contribuyente. Se envía la modificación a fuente dinámica")
                        .addParametersItem(new Parameter()
                                .name("id")
                                .in("path")
                                .description("ID del hecho a editar")
                                .required(true)
                                .schema(new StringSchema())
                        )
                        .requestBody(new io.swagger.v3.oas.models.parameters.RequestBody()
                                .required(true)
                                .content(new Content()
                                        .addMediaType("application/json",
                                                new MediaType()
                                                        .schema(new ObjectSchema()
                                                                .addProperty("titulo", new StringSchema())
                                                                .addProperty("descripcion", new StringSchema())
                                                                .addProperty("latitud", new NumberSchema().format("double"))
                                                                .addProperty("longitud", new NumberSchema().format("double"))
                                                                .example(Map.of(
                                                                        "titulo", "Incendio forestal actualizado",
                                                                        "descripcion", "Descripción actualizada del incendio",
                                                                        "latitud", -31.4201,
                                                                        "longitud", -64.1888
                                                                ))
                                                        )
                                        )
                                )
                        )
                        .responses(new ApiResponses()
                                .addApiResponse("200", new ApiResponse()
                                        .description("Hecho actualizado exitosamente")
                                        .content(new Content()
                                                .addMediaType("application/json",
                                                        new MediaType()
                                                                .schema(new ObjectSchema()
                                                                        .addProperty("id", new StringSchema().example("hecho-123"))
                                                                        .addProperty("titulo", new StringSchema().example("Incendio forestal actualizado"))
                                                                        .addProperty("latitud", new NumberSchema().example(-31.4201))
                                                                        .addProperty("longitud", new NumberSchema().example(-64.1888))
                                                                )
                                                )
                                        )
                                )
                        )
                )
        );

        paths.addPathItem("/apiPublica/hechos/index", new PathItem()
                .get(new Operation()
                        .tags(List.of("hecho-controller"))
                        .summary("Autocompletar hechos / index")
                        .description("Devuelve datos para autocompletar las recomendaciones de busqueda de hechos")
                        .responses(new ApiResponses()
                                .addApiResponse("200", new ApiResponse()
                                        .description("OK")
                                        .content(new Content().addMediaType("application/json",
                                                new MediaType().schema(
                                                        new ArraySchema()
                                                                .items(new StringSchema().example("Titulo de hecho de prueba"))
                                                )
                                        ))
                                )
                        )
                )
        );

        paths.addPathItem("/apiPublica/colecciones", new PathItem()
                .get(new Operation()
                        .tags(List.of("coleccion-controller"))
                        .summary("Mostrar todas las colecciones")
                        .description("Devuelve la lista completa de colecciones con paginación")
                        .responses(new ApiResponses()
                                .addApiResponse("200", new ApiResponse()
                                        .description("OK")
                                        .content(new Content().addMediaType("application/json",
                                                new MediaType().schema(
                                                        new ObjectSchema()
                                                                .addProperty("totalElements", new IntegerSchema().example(0))
                                                                .addProperty("totalPages", new IntegerSchema().example(0))
                                                                .addProperty("first", new BooleanSchema().example(true))
                                                                .addProperty("last", new BooleanSchema().example(true))
                                                                .addProperty("size", new IntegerSchema().example(0))
                                                                .addProperty("number", new IntegerSchema().example(0))
                                                                .addProperty("numberOfElements", new IntegerSchema().example(0))
                                                                .addProperty("empty", new BooleanSchema().example(true))
                                                                .addProperty("content", new ArraySchema()
                                                                        .items(new ObjectSchema()
                                                                                .addProperty("id", new StringSchema().example("string"))
                                                                                .addProperty("titulo", new StringSchema().example("string"))
                                                                                .addProperty("descripcion", new StringSchema().example("string"))
                                                                                .addProperty("criteriosDePertenencia", new ArraySchema()
                                                                                        .items(new ObjectSchema()
                                                                                                .addProperty("id", new IntegerSchema().example(0))
                                                                                        )
                                                                                )
                                                                                .addProperty("fuentes", new ArraySchema()
                                                                                        .items(new ObjectSchema()
                                                                                                .addProperty("id", new StringSchema().example("string"))
                                                                                                .addProperty("alias", new StringSchema().example("string"))
                                                                                        )
                                                                                )
                                                                                .addProperty("tipoAlgoritmoConsenso", new StringSchema().example("IRRESTRICTO"))
                                                                        )
                                                                )
                                                                .addProperty("pageable", new ObjectSchema()
                                                                        .addProperty("offset", new IntegerSchema().example(0))
                                                                        .addProperty("pageNumber", new IntegerSchema().example(0))
                                                                        .addProperty("pageSize", new IntegerSchema().example(0))
                                                                        .addProperty("sort", new ObjectSchema()
                                                                                .addProperty("empty", new BooleanSchema().example(true))
                                                                                .addProperty("sorted", new BooleanSchema().example(true))
                                                                                .addProperty("unsorted", new BooleanSchema().example(true))
                                                                        )
                                                                        .addProperty("unpaged", new BooleanSchema().example(true))
                                                                        .addProperty("paged", new BooleanSchema().example(true))
                                                                )
                                                                .addProperty("sort", new ObjectSchema()
                                                                        .addProperty("empty", new BooleanSchema().example(true))
                                                                        .addProperty("sorted", new BooleanSchema().example(true))
                                                                        .addProperty("unsorted", new BooleanSchema().example(true))
                                                                )
                                                )
                                        ))
                                )
                        )
                )
        );

        paths.addPathItem("/apiPublica/colecciones/{id}", new PathItem()
                .get(new Operation()
                        .tags(List.of("coleccion-controller"))
                        .summary("Mostrar colección por ID")
                        .description("Devuelve una colección específica según su ID")
                        .addParametersItem(new Parameter()
                                .name("id")
                                .in("path")
                                .required(true)
                                .schema(new IntegerSchema())
                                .description("ID de la colección")
                        )
                        .responses(new ApiResponses()
                                .addApiResponse("200", new ApiResponse()
                                        .description("OK")
                                        .content(new Content().addMediaType("application/json",
                                                new MediaType().schema(
                                                        new ObjectSchema()
                                                                .addProperty("id", new StringSchema().example("string"))
                                                                .addProperty("titulo", new StringSchema().example("string"))
                                                                .addProperty("descripcion", new StringSchema().example("string"))
                                                                .addProperty("criteriosDePertenencia", new ArraySchema()
                                                                        .items(new ObjectSchema()
                                                                                .addProperty("id", new IntegerSchema().example(0))
                                                                        )
                                                                )
                                                                .addProperty("fuentes", new ArraySchema()
                                                                        .items(new ObjectSchema()
                                                                                .addProperty("id", new StringSchema().example("string"))
                                                                                .addProperty("alias", new StringSchema().example("string"))
                                                                        )
                                                                )
                                                                .addProperty("tipoAlgoritmoConsenso", new StringSchema().example("IRRESTRICTO"))
                                                )
                                        ))
                                )
                        )
                )
        );
        paths.addPathItem("/apiPublica/colecciones/{id}/hechosIrrestrictos", new PathItem()
                .get(new Operation()
                        .tags(List.of("coleccion-controller"))
                        .summary("Mostrar hechos irrestrictos de la colección")
                        .description("Devuelve los hechos irrestrictos asociados a una colección")
                        .addParametersItem(new Parameter()
                                .name("id")
                                .in("path")
                                .required(true)
                                .schema(new IntegerSchema())
                                .description("ID de la colección")
                        )
                        .addParametersItem(new Parameter()
                                .name("categoria")
                                .in("query")
                                .required(false)
                                .schema(new StringSchema())
                                .description("Filtra por categoría")
                        )
                        .addParametersItem(new Parameter()
                                .name("fechaReporteDesde")
                                .in("query")
                                .required(false)
                                .schema(new StringSchema().format("date"))
                                .description("Filtra por fecha de reporte desde")
                        )
                        .addParametersItem(new Parameter()
                                .name("fechaReporteHasta")
                                .in("query")
                                .required(false)
                                .schema(new StringSchema().format("date"))
                                .description("Filtra por fecha de reporte hasta")
                        )
                        .addParametersItem(new Parameter()
                                .name("fechaAcontecimientoDesde")
                                .in("query")
                                .required(false)
                                .schema(new StringSchema().format("date-time"))
                                .description("Filtra por fecha de acontecimiento desde")
                        )
                        .addParametersItem(new Parameter()
                                .name("fechaAcontecimientoHasta")
                                .in("query")
                                .required(false)
                                .schema(new StringSchema().format("date-time"))
                                .description("Filtra por fecha de acontecimiento hasta")
                        )
                        .addParametersItem(new Parameter()
                                .name("latitud")
                                .in("query")
                                .required(false)
                                .schema(new NumberSchema().format("double"))
                                .description("Filtra por latitud")
                        )
                        .addParametersItem(new Parameter()
                                .name("longitud")
                                .in("query")
                                .required(false)
                                .schema(new NumberSchema().format("double"))
                                .description("Filtra por longitud")
                        )
                        .addParametersItem(new Parameter()
                                .name("radio")
                                .in("query")
                                .required(false)
                                .schema(new NumberSchema().format("double"))
                                .description("Filtra por radio")
                        )
                        .addParametersItem(new Parameter()
                                .name("search")
                                .in("query")
                                .required(false)
                                .schema(new StringSchema())
                                .description("Término de búsqueda")
                        )
                        .addParametersItem(new Parameter()
                                .name("page")
                                .in("query")
                                .required(false)
                                .schema(new IntegerSchema().example(0))
                                .description("Número de página")
                        )
                        .addParametersItem(new Parameter()
                                .name("size")
                                .in("query")
                                .required(false)
                                .schema(new IntegerSchema().example(100))
                                .description("Tamaño de página")
                        )
                        .responses(new ApiResponses()
                                .addApiResponse("200", paginatedHechosResponse)
                        )
                )
        );

        paths.addPathItem("/apiPublica/colecciones/{id}/hechosCurados", new PathItem()
                .get(new Operation()
                        .tags(List.of("coleccion-controller"))
                        .summary("Mostrar hechos curados de la colección")
                        .description("Devuelve los hechos curados asociados a una colección")
                        .addParametersItem(new Parameter()
                                .name("id")
                                .in("path")
                                .required(true)
                                .schema(new IntegerSchema())
                                .description("ID de la colección")
                        )
                        .addParametersItem(new Parameter()
                                .name("categoria")
                                .in("query")
                                .required(false)
                                .schema(new StringSchema())
                                .description("Filtra por categoría")
                        )
                        .addParametersItem(new Parameter()
                                .name("fechaReporteDesde")
                                .in("query")
                                .required(false)
                                .schema(new StringSchema().format("date"))
                                .description("Filtra por fecha de reporte desde")
                        )
                        .addParametersItem(new Parameter()
                                .name("fechaReporteHasta")
                                .in("query")
                                .required(false)
                                .schema(new StringSchema().format("date"))
                                .description("Filtra por fecha de reporte hasta")
                        )
                        .addParametersItem(new Parameter()
                                .name("fechaAcontecimientoDesde")
                                .in("query")
                                .required(false)
                                .schema(new StringSchema().format("date-time"))
                                .description("Filtra por fecha de acontecimiento desde")
                        )
                        .addParametersItem(new Parameter()
                                .name("fechaAcontecimientoHasta")
                                .in("query")
                                .required(false)
                                .schema(new StringSchema().format("date-time"))
                                .description("Filtra por fecha de acontecimiento hasta")
                        )
                        .addParametersItem(new Parameter()
                                .name("latitud")
                                .in("query")
                                .required(false)
                                .schema(new NumberSchema().format("double"))
                                .description("Filtra por latitud")
                        )
                        .addParametersItem(new Parameter()
                                .name("longitud")
                                .in("query")
                                .required(false)
                                .schema(new NumberSchema().format("double"))
                                .description("Filtra por longitud")
                        )
                        .addParametersItem(new Parameter()
                                .name("radio")
                                .in("query")
                                .required(false)
                                .schema(new NumberSchema().format("double"))
                                .description("Filtra por radio")
                        )
                        .addParametersItem(new Parameter()
                                .name("search")
                                .in("query")
                                .required(false)
                                .schema(new StringSchema())
                                .description("Término de búsqueda")
                        )
                        .addParametersItem(new Parameter()
                                .name("page")
                                .in("query")
                                .required(false)
                                .schema(new IntegerSchema().example(0))
                                .description("Número de página")
                        )
                        .addParametersItem(new Parameter()
                                .name("size")
                                .in("query")
                                .required(false)
                                .schema(new IntegerSchema().example(100))
                                .description("Tamaño de página")
                        )
                        .responses(new ApiResponses()
                                .addApiResponse("200", paginatedHechosResponse
                                )
                        )
                )
        );

        paths.addPathItem("/apiPublica/colecciones/index", new PathItem()
                .get(new Operation()
                        .tags(List.of("coleccion-controller"))
                        .summary("Autocompletar colecciones / índice")
                        .description("Devuelve datos para autocompletar en las busquedas de coleccoines")
                        .responses(new ApiResponses()
                                .addApiResponse("200", new ApiResponse()
                                        .description("OK")
                                        .content(new Content().addMediaType("application/json",
                                                new MediaType().schema(
                                                        new ArraySchema()
                                                                .items(new StringSchema().example("Titulo de hecho de prueba"))
                                                )
                                        ))
                                )
                        )
                )
        );


        paths.addPathItem("/apiPublica/provinciasConMasHechosDeColeccion", new PathItem()
                .get(new Operation()
                        .tags(List.of("estadisticas-controller"))
                        .summary("Provincias con más hechos de colección")
                        .description("Obtiene un ranking de provincias con más hechos para una colección específica. Se conecta al servicio de estadísticas")
                        .addParametersItem(new Parameter()
                                .name("idColeccion")
                                .in("query")
                                .description("ID de la colección")
                                .required(false)
                                .schema(new StringSchema())
                        )
                        .addParametersItem(new Parameter()
                                .name("page")
                                .in("query")
                                .description("Número de página")
                                .required(false)
                                .schema(new IntegerSchema()._default(0))
                        )
                        .addParametersItem(new Parameter()
                                .name("limit")
                                .in("query")
                                .description("Cantidad de resultados")
                                .required(false)
                                .schema(new IntegerSchema()._default(1))
                        )
                        .addParametersItem(new Parameter()
                                .name("Accept")
                                .in("header")
                                .description("Formato de respuesta (application/json o text/csv)")
                                .required(false)
                                .schema(new StringSchema()._default("application/json"))
                        )
                        .responses(new ApiResponses()
                                .addApiResponse("200", new ApiResponse()
                                        .description("OK")
                                        .content(new Content()
                                                .addMediaType("application/json",
                                                        new MediaType()
                                                                .schema(new ArraySchema()
                                                                        .items(new ObjectSchema()
                                                                                .addProperty("provincia", new StringSchema().example("Buenos Aires"))
                                                                                .addProperty("cantidad", new IntegerSchema().example(150))
                                                                        )
                                                                )
                                                )
                                                .addMediaType("text/csv",
                                                        new MediaType()
                                                                .schema(new StringSchema().example("provincia,cantidad\nBuenos Aires,150\n"))
                                                )
                                        )
                                )
                        )
                ));

        paths.addPathItem("/apiPublica/categoriasConMasHechos", new PathItem()
                .get(new Operation()
                        .tags(List.of("estadisticas-controller"))
                        .summary("Categorías con más hechos reportados")
                        .description("Obtiene un ranking de categorías con más hechos reportados. Se conecta al servicio de estadísticas")
                        .addParametersItem(new Parameter()
                                .name("page")
                                .in("query")
                                .description("Número de página")
                                .required(false)
                                .schema(new IntegerSchema()._default(0))
                        )
                        .addParametersItem(new Parameter()
                                .name("limit")
                                .in("query")
                                .description("Cantidad de resultados")
                                .required(false)
                                .schema(new IntegerSchema()._default(1))
                        )
                        .addParametersItem(new Parameter()
                                .name("Accept")
                                .in("header")
                                .description("Formato de respuesta (application/json o text/csv)")
                                .required(false)
                                .schema(new StringSchema()._default("application/json"))
                        )
                        .responses(new ApiResponses()
                                .addApiResponse("200", new ApiResponse()
                                        .description("OK")
                                        .content(new Content()
                                                .addMediaType("application/json",
                                                        new MediaType()
                                                                .schema(new ArraySchema()
                                                                        .items(new ObjectSchema()
                                                                                .addProperty("categoria", new StringSchema().example("Incendio"))
                                                                                .addProperty("cantidad", new IntegerSchema().example(320))
                                                                        )
                                                                )
                                                )
                                                .addMediaType("text/csv",
                                                        new MediaType()
                                                                .schema(new StringSchema().example("categoria,cantidad\nIncendio,320\n"))
                                                )
                                        )
                                )
                        )
                ));

        paths.addPathItem("/apiPublica/provinciasConMasHechosDeCategoria", new PathItem()
                .get(new Operation()
                        .tags(List.of("estadisticas-controller"))
                        .summary("Provincias con más hechos de una categoría")
                        .description("Obtiene un ranking de provincias con más hechos para una categoría específica. Se conecta al servicio de estadísticas")
                        .addParametersItem(new Parameter()
                                .name("nombreCategoria")
                                .in("query")
                                .description("Nombre de la categoría")
                                .required(false)
                                .schema(new StringSchema())
                        )
                        .addParametersItem(new Parameter()
                                .name("page")
                                .in("query")
                                .description("Número de página")
                                .required(false)
                                .schema(new IntegerSchema()._default(0))
                        )
                        .addParametersItem(new Parameter()
                                .name("limit")
                                .in("query")
                                .description("Cantidad de resultados")
                                .required(false)
                                .schema(new IntegerSchema()._default(1))
                        )
                        .addParametersItem(new Parameter()
                                .name("Accept")
                                .in("header")
                                .description("Formato de respuesta (application/json o text/csv)")
                                .required(false)
                                .schema(new StringSchema()._default("application/json"))
                        )
                        .responses(new ApiResponses()
                                .addApiResponse("200", new ApiResponse()
                                        .description("OK")
                                        .content(new Content()
                                                .addMediaType("application/json",
                                                        new MediaType()
                                                                .schema(new ArraySchema()
                                                                        .items(new ObjectSchema()
                                                                                .addProperty("provincia", new StringSchema().example("Córdoba"))
                                                                                .addProperty("cantidad", new IntegerSchema().example(75))
                                                                        )
                                                                )
                                                )
                                                .addMediaType("text/csv",
                                                        new MediaType()
                                                                .schema(new StringSchema().example("provincia,cantidad\nCórdoba,75\n"))
                                                )
                                        )
                                )
                        )
                ));

        paths.addPathItem("/apiPublica/horaConMasHechosDeCategoria", new PathItem()
                .get(new Operation()
                        .tags(List.of("estadisticas-controller"))
                        .summary("Hora con más hechos de una categoría")
                        .description("Obtiene un ranking de horas del día con más hechos para una categoría específica. Se conecta al servicio de estadísticas")
                        .addParametersItem(new Parameter()
                                .name("nombreCategoria")
                                .in("query")
                                .description("Nombre de la categoría")
                                .required(false)
                                .schema(new StringSchema())
                        )
                        .addParametersItem(new Parameter()
                                .name("page")
                                .in("query")
                                .description("Número de página")
                                .required(false)
                                .schema(new IntegerSchema()._default(0))
                        )
                        .addParametersItem(new Parameter()
                                .name("limit")
                                .in("query")
                                .description("Cantidad de resultados")
                                .required(false)
                                .schema(new IntegerSchema()._default(1))
                        )
                        .addParametersItem(new Parameter()
                                .name("Accept")
                                .in("header")
                                .description("Formato de respuesta (application/json o text/csv)")
                                .required(false)
                                .schema(new StringSchema()._default("application/json"))
                        )
                        .responses(new ApiResponses()
                                .addApiResponse("200", new ApiResponse()
                                        .description("OK")
                                        .content(new Content()
                                                .addMediaType("application/json",
                                                        new MediaType()
                                                                .schema(new ArraySchema()
                                                                        .items(new ObjectSchema()
                                                                                .addProperty("hora", new IntegerSchema().example(14))
                                                                                .addProperty("cantidad", new IntegerSchema().example(45))
                                                                        )
                                                                )
                                                )
                                                .addMediaType("text/csv",
                                                        new MediaType()
                                                                .schema(new StringSchema().example("hora,cantidad\n14,45\n"))
                                                )
                                        )
                                )
                        )
                ));

        paths.addPathItem("/apiPublica/solicitudesDeEliminacionSpam", new PathItem()
                .get(new Operation()
                        .tags(List.of("estadisticas-controller"))
                        .summary("Solicitudes de eliminación marcadas como spam")
                        .description("Obtiene las solicitudes de eliminación que fueron marcadas como spam. Se conecta al servicio de estadísticas")
                        .addParametersItem(new Parameter()
                                .name("Accept")
                                .in("header")
                                .description("Formato de respuesta (application/json o text/csv)")
                                .required(false)
                                .schema(new StringSchema()._default("application/json"))
                        )
                        .responses(new ApiResponses()
                                .addApiResponse("200", new ApiResponse()
                                        .description("OK")
                                        .content(new Content()
                                                .addMediaType("application/json",
                                                        new MediaType()
                                                                .schema(new ArraySchema()
                                                                        .items(new ObjectSchema()
                                                                                .addProperty("id", new IntegerSchema().example(1))
                                                                                .addProperty("solicitanteId", new IntegerSchema().example(5))
                                                                                .addProperty("hechoId", new StringSchema().example("hecho-123"))
                                                                                .addProperty("motivo", new StringSchema().example("Contenido spam"))
                                                                                .addProperty("estado", new StringSchema().example("SPAM"))
                                                                        )
                                                                )
                                                )
                                                .addMediaType("text/csv",
                                                        new MediaType()
                                                                .schema(new StringSchema().example("id,solicitanteId,hechoId,motivo,estado\n1,5,hecho-123,Contenido spam,SPAM\n"))
                                                )
                                        )
                                )
                        )
                ));

        paths.addPathItem("/apiPublica/estadisticas/categorias", new PathItem()
                .get(new Operation()
                        .tags(List.of("estadisticas-controller"))
                        .summary("Categorías disponibles")
                        .description("Obtiene la lista de categorías disponibles con búsqueda opcional. Se conecta al servicio de estadísticas")
                        .addParametersItem(new Parameter()
                                .name("search")
                                .in("query")
                                .description("Texto de búsqueda para filtrar categorías")
                                .required(false)
                                .schema(new StringSchema())
                        )
                        .addParametersItem(new Parameter()
                                .name("page")
                                .in("query")
                                .description("Número de página")
                                .required(false)
                                .schema(new IntegerSchema()._default(0))
                        )
                        .addParametersItem(new Parameter()
                                .name("limit")
                                .in("query")
                                .description("Cantidad de resultados")
                                .required(false)
                                .schema(new IntegerSchema()._default(10))
                        )
                        .responses(new ApiResponses()
                                .addApiResponse("200", new ApiResponse()
                                        .description("OK")
                                        .content(new Content()
                                                .addMediaType("application/json",
                                                        new MediaType()
                                                                .schema(new ArraySchema()
                                                                        .items(new StringSchema().example("Incendio"))
                                                                )
                                                )
                                        )
                                )
                        )
                ));

        paths.addPathItem("/apiPublica/estadisticas/colecciones", new PathItem()
                .get(new Operation()
                        .tags(List.of("estadisticas-controller"))
                        .summary("Colecciones disponibles")
                        .description("Obtiene la lista de colecciones disponibles con búsqueda opcional. Se conecta al servicio de estadísticas")
                        .addParametersItem(new Parameter()
                                .name("search")
                                .in("query")
                                .description("Texto de búsqueda para filtrar colecciones")
                                .required(false)
                                .schema(new StringSchema())
                        )
                        .addParametersItem(new Parameter()
                                .name("page")
                                .in("query")
                                .description("Número de página")
                                .required(false)
                                .schema(new IntegerSchema()._default(0))
                        )
                        .addParametersItem(new Parameter()
                                .name("limit")
                                .in("query")
                                .description("Cantidad de resultados")
                                .required(false)
                                .schema(new IntegerSchema()._default(10))
                        )
                        .responses(new ApiResponses()
                                .addApiResponse("200", new ApiResponse()
                                        .description("OK")
                                        .content(new Content()
                                                .addMediaType("application/json",
                                                        new MediaType()
                                                                .schema(new ArraySchema()
                                                                        .items(new ObjectSchema()
                                                                                .addProperty("id", new StringSchema().example("col-1"))
                                                                                .addProperty("nombre", new StringSchema().example("Desastres Naturales"))
                                                                        )
                                                                )
                                                )
                                        )
                                )
                        )
                ));

        return new OpenAPI()
                .info(new io.swagger.v3.oas.models.info.Info()
                        .title("API Pública de Metamapa")
                        .version("1.0")
                        .description("""
                                ● Consulta de hechos dentro de una colección.
                                ● Generar una solicitud de eliminación a un hecho.
                                ● Navegación filtrada sobre una colección.
                                ● Navegación curada o irrestricta sobre una colección.
                                ● Reportar un hecho.""")
                        .contact(new io.swagger.v3.oas.models.info.Contact()
                                .name("DDS K3002 Grupo 2")
                                .email("aherzkovich@frba.utn.edu.ar"))
                        .license(new io.swagger.v3.oas.models.info.License()
                                .name("MIT")
                                .url("https://opensource.org/licenses/MIT"))
                )
                .servers(List.of(
                        new io.swagger.v3.oas.models.servers.Server()
                                .url("http://localhost:8085")
                )).paths(paths);
    }
}